require 'rubygems'
require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint'

# You can disable certain puppet-lint checks if you want.
# For more info: http://puppet-lint.com/
# For example:
# PuppetLint.configuration.send("disable_80chars")
