#!/usr/bin/env ruby

#------------------------------------------------------------
# $Id$
#
# run any or all test suites

$:.unshift '.'
$:.unshift '../lib'

# if we're not in the library trunk, then add that to the lib search path
if Dir.getwd !~ %r{blink/library}
    $:.unshift '../../../library/trunk/lib/'
    $:.unshift '../../../library/trunk/test/'
end

require 'blinktest.rb'

require 'getoptlong'

	#[ "--size",	"-s",			GetoptLong::REQUIRED_ARGUMENT ],
result = GetoptLong.new(
	[ "--help",		"-h",			GetoptLong::NO_ARGUMENT ]
)

usage = "USAGE: %s [--help] <testsuite> <testsuite> .." % $0

result.each { |opt,arg|
	case opt
		when "--help"
			puts usage
			exit
		else
			raise "Invalid option '#{opt}'"
	end
}

$blinkbase = ".."

suites = nil

if ARGV.length != 0
    suites = ARGV
else
    suites = BlinkTestSuite.list
end

suites.each { |suite|
    BlinkTestSuite.new(suite)
}
