#!/bin/bash
# Make temporary build directory, copy target copy of puppet, call rake
USAGE="usage: $0 \"trunk\"|\"tags/<version>\" [rake options]"

if ! [ $1 ]; then
  echo Please specify what puppet version to Rake
  echo $USAGE
  exit
fi

echo Puppet Merge/Rake Script: language/$1 library/$1
TEMP_MAKE_LOCAL_DIR=/tmp/tmp_puppet_rake_$1

# Perform cleanup
if [ -d $TEMP_MAKE_LOCAL_DIR ]; then rm -rf $TEMP_MAKE_LOCAL_DIR; fi
mkdir $TEMP_MAKE_LOCAL_DIR

cp -r language/$1/* $TEMP_MAKE_LOCAL_DIR
cp -r library/$1/* $TEMP_MAKE_LOCAL_DIR
cd $TEMP_MAKE_LOCAL_DIR
shift
rake $@
pwd; ls; ls pkg
