require 'puppet/application'

class Puppet::Application::Filebucket < Puppet::Application

  option("--bucket BUCKET","-b")
  option("--fromdate FROMDATE", "-f")
  option("--todate TODATE", "-t")
  option("--debug","-d")
  option("--local","-l")
  option("--remote","-r")
  option("--verbose","-v")

  attr :args

  def help
    <<-HELP

puppet-filebucket(8) -- Store and retrieve files in a filebucket
========

SYNOPSIS
--------
A stand-alone Puppet filebucket client.


USAGE
-----
puppet filebucket <mode> [-h|--help] [-V|--version] [-d|--debug]
  [-v|--verbose] [-l|--local] [-r|--remote] [-s|--server <server>]
  [-b|--bucket <directory>] [list] [diff] <file> <file> ...

Puppet filebucket can operate in three modes, with only one mode per call:

backup:
  Send one or more files to the specified file bucket. Each sent file is
  printed with its resulting md5 sum.

get:
  Return the text associated with an md5 sum. The text is printed to
  stdout, and only one file can be retrieved at a time.

restore:
  Given a file path and an md5 sum, store the content associated with
  the sum into the specified file path. You can specify an entirely new
  path to this argument; you are not restricted to restoring the content
  to its original location.

list:
  List all files in the current filebucket.

diff:
  Print a diff between two md5 in the filebucket or between a md5sum and its
  matching file.

DESCRIPTION
-----------
This is a stand-alone filebucket client for sending files to a local or
central filebucket.

Note that 'filebucket' defaults to using a network-based filebucket
available on the server named 'puppet'. To use this, you'll have to be
running as a user with valid Puppet certificates. Alternatively, you can
use your local file bucket by specifying '--local'.


OPTIONS
-------
Note that any configuration parameter that's valid in the configuration
file is also a valid long argument. For example, 'ssldir' is a valid
configuration parameter, so you can specify '--ssldir <directory>' as an
argument.

See the configuration file documentation at
http://docs.puppetlabs.com/references/stable/configuration.html for the
full list of acceptable parameters. A commented list of all
configuration options can also be generated by running puppet with
'--genconfig'.

* --debug:
  Enable full debugging.

* --help:
  Print this help message

* --local:
  Use the local filebucket. This will use the default configuration
  information.

* --remote:
  Use a remote filebucket. This will use the default configuration
  information.

* --server:
  The server to send the file to, instead of locally.

* --verbose:
  Print extra information.

* --version:
  Print version information.

* --fromdate:
  Select bucket files from 'fromdate' (list only)

* --todate:
   Select bucket files until 'todate' (list only)

EXAMPLE
-------
    $ puppet filebucket backup /etc/passwd
    /etc/passwd: 429b225650b912a2ee067b0a4cf1e949
    $ puppet filebucket restore /tmp/passwd 429b225650b912a2ee067b0a4cf1e949

    $ filebucket -l list --fromdate "2010-09-14 12:04:44"
    8486f097057436a7d675f68c327f625d 2010-09-14 12:04:48 /etc/fstab
    0b42e60883a33034f1bec7dba55e5018 2010-10-05 13:29:56 /etc/gitconfig
    9f537de00f864ce8e8b06293f2f6a4a8 2010-10-05 13:33:17 /etc/gitconfig
    32556201d742291bb64fec741ad7b128 2010-10-05 17:27:27 /etc/gitconfig
 
    $  filebucket -l diff c4cae6862561d1f605e8ba5acc7d07cd
    --- /tmp/puppet-diffing-puppet.conf.21267.0     2010-10-11 13:42:22.000000000 +0200
    +++ /etc/puppet/puppet.conf     2010-01-28 04:48:33.000000000 +0100
    @@ -27,4 +27,4 @@
      # extension indicating the cache format is added automatically.
      # The default value is '$confdir/localconfig'.
      localconfig = $vardir/localconfig
    - environment = production
    + environment = testing


AUTHOR
------
Luke Kanies


COPYRIGHT
---------
Copyright (c) 2011 Puppet Labs, LLC Licensed under the Apache 2.0 License

    HELP
  end


  def run_command
    @args = command_line.args
    command = args.shift
    return send(command) if %w{get backup restore list diff}.include? command
    help
  end

  def get
    md5 = args.shift
    out = @client.getfile(md5)
    print out
  end

  def backup
    raise "You must specify a file to back up" unless args.length > 0

    args.each do |file|
      unless FileTest.exists?(file)
        $stderr.puts "#{file}: no such file"
        next
      end
      unless FileTest.readable?(file)
        $stderr.puts "#{file}: cannot read file"
        next
      end
      md5 = @client.backup(file)
      puts "#{file}: #{md5}"
    end
  end

  def restore
    file = args.shift
    md5 = args.shift
    @client.restore(file, md5)
  end

  def list
    fromdate = options[:fromdate] || "0:0:0 1-1-1970"
    todate = options[:todate] || Time.new.httpdate.to_s
    out = @client.list(fromdate, todate)
    print out
  end

  def diff
    md5a = args.shift
    md5b = args.shift || ''
    if md5a
      Puppet.info("Comparing #{md5a} #{md5b}")
      print @client.diff(md5a, md5b)
    else
      $stderr.puts "Need at last one md5: filebucket diff #{ARGV} <md5a> <md5b>"
    end
  end

  def setup
    Puppet::Log.newdestination(:console)

    @client = nil
    @server = nil

    Signal.trap(:INT) do
      $stderr.puts "Cancelling"
      exit(1)
    end

    if options[:debug]
      Puppet::Log.level = :debug
    elsif options[:verbose]
      Puppet::Log.level = :info
    end

      exit(Puppet.settings.print_configs ? 0 : 1) if Puppet.settings.print_configs?

    require 'puppet/file_bucket/dipper'
    begin
      if options[:local] or options[:bucket]
        path = options[:bucket] || Puppet[:bucketdir]
        @client = Puppet::FileBucket::Dipper.new(:Path => path)
      else
        @client = Puppet::FileBucket::Dipper.new(:Server => Puppet[:server])
      end
    rescue => detail
      Puppet.log_exception(detail)
      exit(1)
    end
  end

end

