#!/bin/bash
#
# Make sure that old puppet cruft is removed
# This also allows us to downgrade puppet as
# it's more likely that installing old versions
# over new will cause issues.
#
# ${3} is the destination volume so that this works correctly
# when being installed to volumes other than the current OS.

/bin/rm -Rf "${3}{SITELIBDIR}/puppet"
/bin/rm -Rf "${3}{SITELIBDIR}/puppet.rb"
