#!/bin/bash
#
# Make sure that old puppet cruft is removed
# This also allows us to downgrade puppet as
# it's more likely that installing old versions
# over new will cause issues.
#
# ${3} is the destination volume so that this works correctly
# when being installed to volumes other than the current OS.

/bin/rm -Rf "${3}{SITELIBDIR}/puppet"
/bin/rm -Rf "${3}{SITELIBDIR}/puppet.rb"

# remove old doc files

/bin/rm -Rf "${3}/usr/share/doc/puppet"

# In puppet 0.24.x these executables lived in bindir, but in 0.25.x they
# have been moved to sbindir. This cleans out old ones before installing.
/bin/rm -Rf "${3}{BINDIR}/puppetca"
/bin/rm -Rf "${3}{BINDIR}/puppetd"
/bin/rm -Rf "${3}{BINDIR}/puppetmasterd"
/bin/rm -Rf "${3}{BINDIR}/puppetqd"
/bin/rm -Rf "${3}{BINDIR}/puppetrun"