#!/bin/sh

# $Id$

script=$0
path=`echo $script | sed 's/etc..*/bin/'`

PATH=$PATH:$path

case "$1" in
    start)
        sleeper
	;;
    stop)
        kill `ps -ef | grep -v grep | grep sleeper | grep perl | awk '{print $2}'`
	;;
    status)
        output=`ps -ef | grep -v grep | grep -v init.d | grep sleeper`
        exit $?
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
