.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EXTLOOKUP2HIERA" "8" "May 2015" "Puppet Labs, LLC" "Puppet manual"
.
.SH "NAME"
\fBextlookup2hiera\fR
.
.P
Converter for extlookup CSV files into Hiera JSON and YAML files \-i, \-\-in FILE Input CSV file \-o, \-\-out FILE Output Hiera file \-j, \-\-json Create JSON format file
