.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET\-FILEBUCKET" "8" "June 2011" "Puppet Labs, LLC" "Puppet manual"
.
.SH "NAME"
\fBpuppet\-filebucket\fR \- Store and retrieve files in a filebucket
.
.SH "SYNOPSIS"
A stand\-alone Puppet filebucket client\.
.
.SH "USAGE"
puppet filebucket \fImode\fR [\-h|\-\-help] [\-V|\-\-version] [\-d|\-\-debug] [\-v|\-\-verbose] [\-l|\-\-local] [\-r|\-\-remote] [\-s|\-\-server \fIserver\fR] [\-b|\-\-bucket \fIdirectory\fR] \fIfile\fR \fIfile\fR \.\.\.
.
.P
Puppet filebucket can operate in three modes, with only one mode per call:
.
.P
backup: Send one or more files to the specified file bucket\. Each sent file is printed with its resulting md5 sum\.
.
.P
get: Return the text associated with an md5 sum\. The text is printed to stdout, and only one file can be retrieved at a time\.
.
.P
restore: Given a file path and an md5 sum, store the content associated with the sum into the specified file path\. You can specify an entirely new path to this argument; you are not restricted to restoring the content to its original location\.
.
.SH "DESCRIPTION"
This is a stand\-alone filebucket client for sending files to a local or central filebucket\.
.
.P
Note that \'filebucket\' defaults to using a network\-based filebucket available on the server named \'puppet\'\. To use this, you\'ll have to be running as a user with valid Puppet certificates\. Alternatively, you can use your local file bucket by specifying \'\-\-local\'\.
.
.SH "OPTIONS"
Note that any configuration parameter that\'s valid in the configuration file is also a valid long argument\. For example, \'ssldir\' is a valid configuration parameter, so you can specify \'\-\-ssldir \fIdirectory\fR\' as an argument\.
.
.P
See the configuration file documentation at http://docs\.puppetlabs\.com/references/stable/configuration\.html for the full list of acceptable parameters\. A commented list of all configuration options can also be generated by running puppet with \'\-\-genconfig\'\.
.
.TP
\-\-debug
Enable full debugging\.
.
.TP
\-\-help
Print this help message
.
.TP
\-\-local
Use the local filebucket\. This will use the default configuration information\.
.
.TP
\-\-remote
Use a remote filebucket\. This will use the default configuration information\.
.
.TP
\-\-server
The server to send the file to, instead of locally\.
.
.TP
\-\-verbose
Print extra information\.
.
.TP
\-\-version
Print version information\.
.
.SH "EXAMPLE"
.
.nf

$ puppet filebucket backup /etc/passwd
/etc/passwd: 429b225650b912a2ee067b0a4cf1e949
$ puppet filebucket restore /tmp/passwd 429b225650b912a2ee067b0a4cf1e949
.
.fi
.
.SH "AUTHOR"
Luke Kanies
.
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Labs, LLC Licensed under the Apache 2\.0 License
