.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET\-KICK" "8" "June 2011" "Puppet Labs, LLC" "Puppet manual"
.
.SH "NAME"
\fBpuppet\-kick\fR \- Remotely control puppet agent
.
.SH "SYNOPSIS"
Trigger a puppet agent run on a set of hosts\.
.
.SH "USAGE"
puppet kick [\-a|\-\-all] [\-c|\-\-class \fIclass\fR] [\-d|\-\-debug] [\-f|\-\-foreground] [\-h|\-\-help] [\-\-host \fIhost\fR] [\-\-no\-fqdn] [\-\-ignoreschedules] [\-t|\-\-tag \fItag\fR] [\-\-test] [\-p|\-\-ping] \fIhost\fR [\fIhost\fR [\.\.\.]]
.
.SH "DESCRIPTION"
This script can be used to connect to a set of machines running \'puppet agent\' and trigger them to run their configurations\. The most common usage would be to specify a class of hosts and a set of tags, and \'puppet kick\' would look up in LDAP all of the hosts matching that class, then connect to each host and trigger a run of all of the objects with the specified tags\.
.
.P
If you are not storing your host configurations in LDAP, you can specify hosts manually\.
.
.P
You will most likely have to run \'puppet kick\' as root to get access to the SSL certificates\.
.
.P
\'puppet kick\' reads \'puppet master\'\'s configuration file, so that it can copy things like LDAP settings\.
.
.SH "USAGE NOTES"
Puppet kick is useless unless puppet agent is listening for incoming connections and allowing access to the \fBrun\fR endpoint\. This entails starting the agent with \fBlisten = true\fR in its puppet\.conf file, and allowing access to the \fB/run\fR path in its auth\.conf file; see \fBhttp://docs\.puppetlabs\.com/guides/rest_auth_conf\.html\fR for more details\.
.
.P
Additionally, due to a known bug, you must make sure a namespaceauth\.conf file exists in puppet agent\'s $confdir\. This file will not be consulted, and may be left empty\.
.
.SH "OPTIONS"
Note that any configuration parameter that\'s valid in the configuration file is also a valid long argument\. For example, \'ssldir\' is a valid configuration parameter, so you can specify \'\-\-ssldir \fIdirectory\fR\' as an argument\.
.
.P
See the configuration file documentation at http://docs\.puppetlabs\.com/references/latest/configuration\.html for the full list of acceptable parameters\. A commented list of all configuration options can also be generated by running puppet master with \'\-\-genconfig\'\.
.
.TP
\-\-all
Connect to all available hosts\. Requires LDAP support at this point\.
.
.TP
\-\-class
Specify a class of machines to which to connect\. This only works if you have LDAP configured, at the moment\.
.
.TP
\-\-debug
Enable full debugging\.
.
.TP
\-\-foreground
Run each configuration in the foreground; that is, when connecting to a host, do not return until the host has finished its run\. The default is false\.
.
.TP
\-\-help
Print this help message
.
.TP
\-\-host
A specific host to which to connect\. This flag can be specified more than once\.
.
.TP
\-\-ignoreschedules
Whether the client should ignore schedules when running its configuration\. This can be used to force the client to perform work it would not normally perform so soon\. The default is false\.
.
.TP
\-\-parallel
How parallel to make the connections\. Parallelization is provided by forking for each client to which to connect\. The default is 1, meaning serial execution\.
.
.TP
\-\-tag
Specify a tag for selecting the objects to apply\. Does not work with the \-\-test option\.
.
.TP
\-\-test
Print the hosts you would connect to but do not actually connect\. This option requires LDAP support at this point\.
.
.TP
\-\-ping
Do a ICMP echo against the target host\. Skip hosts that don\'t respond to ping\.
.
.SH "EXAMPLE"
.
.nf

$ sudo puppet kick \-p 10 \-t remotefile \-t webserver host1 host2
.
.fi
.
.SH "AUTHOR"
Luke Kanies
.
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Labs, LLC Licensed under the Apache 2\.0 License
