.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET\-APPLY" "8" "May 2015" "Puppet Labs, LLC" "Puppet manual"
.
.SH "NAME"
\fBpuppet\-apply\fR \- Apply Puppet manifests locally
.
.SH "SYNOPSIS"
Applies a standalone Puppet manifest to the local system\.
.
.SH "USAGE"
puppet apply [\-h|\-\-help] [\-V|\-\-version] [\-d|\-\-debug] [\-v|\-\-verbose] [\-e|\-\-execute] [\-\-detailed\-exitcodes] [\-L|\-\-loadclasses] [\-l|\-\-logdest syslog|eventlog|\fIFILE\fR|console] [\-\-noop] [\-\-catalog \fIcatalog\fR] [\-\-write\-catalog\-summary] \fIfile\fR
.
.SH "DESCRIPTION"
This is the standalone puppet execution tool; use it to apply individual manifests\.
.
.P
When provided with a modulepath, via command line or config file, puppet apply can effectively mimic the catalog that would be served by puppet master with access to the same modules, although there are some subtle differences\. When combined with scheduling and an automated system for pushing manifests, this can be used to implement a serverless Puppet site\.
.
.P
Most users should use \'puppet agent\' and \'puppet master\' for site\-wide manifests\.
.
.SH "OPTIONS"
Note that any setting that\'s valid in the configuration file is also a valid long argument\. For example, \'tags\' is a valid setting, so you can specify \'\-\-tags \fIclass\fR,\fItag\fR\' as an argument\.
.
.P
See the configuration file documentation at https://docs\.puppetlabs\.com/references/stable/configuration\.html for the full list of acceptable parameters\. A commented list of all configuration options can also be generated by running puppet with \'\-\-genconfig\'\.
.
.IP "\(bu" 4
\-\-debug: Enable full debugging\.
.
.IP "\(bu" 4
\-\-detailed\-exitcodes: Provide transaction information via exit codes\. If this is enabled, an exit code of \'2\' means there were changes, an exit code of \'4\' means there were failures during the transaction, and an exit code of \'6\' means there were both changes and failures\.
.
.IP "\(bu" 4
\-\-help: Print this help message
.
.IP "\(bu" 4
\-\-loadclasses: Load any stored classes\. \'puppet agent\' caches configured classes (usually at /etc/puppetlabs/puppet/classes\.txt), and setting this option causes all of those classes to be set in your puppet manifest\.
.
.IP "\(bu" 4
\-\-logdest: Where to send log messages\. Choose between \'syslog\' (the POSIX syslog service), \'eventlog\' (the Windows Event Log), \'console\', or the path to a log file\. Defaults to \'console\'\.
.
.IP
A path ending with \'\.json\' will receive structured output in JSON format\. The log file will not have an ending \']\' automatically written to it due to the appending nature of logging\. It must be appended manually to make the content valid JSON\.
.
.IP "\(bu" 4
\-\-noop: Use \'noop\' mode where Puppet runs in a no\-op or dry\-run mode\. This is useful for seeing what changes Puppet will make without actually executing the changes\.
.
.IP "\(bu" 4
\-\-execute: Execute a specific piece of Puppet code
.
.IP "\(bu" 4
\-\-test: Enable the most common options used for testing\. These are \'verbose\', \'detailed\-exitcodes\' and \'show_diff\'\.
.
.IP "\(bu" 4
\-\-verbose: Print extra information\.
.
.IP "\(bu" 4
\-\-catalog: Apply a JSON catalog (such as one generated with \'puppet master \-\-compile\')\. You can either specify a JSON file or pipe in JSON from standard input\.
.
.IP "\(bu" 4
\-\-write\-catalog\-summary After compiling the catalog saves the resource list and classes list to the node in the state directory named classes\.txt and resources\.txt
.
.IP "" 0
.
.SH "EXAMPLE"
.
.nf

$ puppet apply \-l /tmp/manifest\.log manifest\.pp
$ puppet apply \-\-modulepath=/root/dev/modules \-e "include ntpd::server"
$ puppet apply \-\-catalog catalog\.json
.
.fi
.
.SH "AUTHOR"
Luke Kanies
.
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Labs, LLC Licensed under the Apache 2\.0 License
