.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET\-DOC" "8" "May 2015" "Puppet Labs, LLC" "Puppet manual"
.
.SH "NAME"
\fBpuppet\-doc\fR \- Generate Puppet references
.
.SH "SYNOPSIS"
Generates a reference for all Puppet types\. Largely meant for internal Puppet Labs use\. (Deprecated)
.
.SH "USAGE"
puppet doc [\-h|\-\-help] [\-l|\-\-list] [\-r|\-\-reference \fIreference\-name\fR]
.
.SH "DESCRIPTION"
This deprecated command generates a Markdown document to stdout describing all installed Puppet types or all allowable arguments to puppet executables\. It is largely meant for internal use and is used to generate the reference document available on the Puppet Labs web site\.
.
.P
For Puppet module documentation (and all other use cases) this command has been superseded by the "puppet\-strings" module \- see https://github\.com/puppetlabs/puppetlabs\-strings for more information\.
.
.P
This command (puppet\-doc) will be removed once the puppetlabs internal documentation processing pipeline is completely based on puppet\-strings\.
.
.SH "OPTIONS"
.
.TP
\-\-help
Print this help message
.
.TP
\-\-reference
Build a particular reference\. Get a list of references by running \'puppet doc \-\-list\'\.
.
.SH "EXAMPLE"
.
.nf

$ puppet doc \-r type > /tmp/type_reference\.markdown
.
.fi
.
.SH "AUTHOR"
Luke Kanies
.
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Labs, LLC Licensed under the Apache 2\.0 License
