.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET\-APPLY" "8" "June 2011" "Puppet Labs, LLC" "Puppet manual"
.
.SH "NAME"
\fBpuppet\-apply\fR \- Apply Puppet manifests locally
.
.SH "SYNOPSIS"
Applies a standalone Puppet manifest to the local system\.
.
.SH "USAGE"
puppet apply [\-h|\-\-help] [\-V|\-\-version] [\-d|\-\-debug] [\-v|\-\-verbose] [\-e|\-\-execute] [\-\-detailed\-exitcodes] [\-l|\-\-logdest \fIfile\fR] [\-\-apply \fIcatalog\fR] \fIfile\fR
.
.SH "DESCRIPTION"
This is the standalone puppet execution tool; use it to apply individual manifests\.
.
.P
When provided with a modulepath, via command line or config file, puppet apply can effectively mimic the catalog that would be served by puppet master with access to the same modules, although there are some subtle differences\. When combined with scheduling and an automated system for pushing manifests, this can be used to implement a serverless Puppet site\.
.
.P
Most users should use \'puppet agent\' and \'puppet master\' for site\-wide manifests\.
.
.SH "OPTIONS"
Note that any configuration parameter that\'s valid in the configuration file is also a valid long argument\. For example, \'modulepath\' is a valid configuration parameter, so you can specify \'\-\-tags \fIclass\fR,\fItag\fR\' as an argument\.
.
.P
See the configuration file documentation at http://docs\.puppetlabs\.com/references/stable/configuration\.html for the full list of acceptable parameters\. A commented list of all configuration options can also be generated by running puppet with \'\-\-genconfig\'\.
.
.TP
\-\-debug
Enable full debugging\.
.
.TP
\-\-detailed\-exitcodes
Provide transaction information via exit codes\. If this is enabled, an exit code of \'2\' means there were changes, and an exit code of \'4\' means that there were failures during the transaction\.
.
.TP
\-\-help
Print this help message
.
.TP
\-\-loadclasses
Load any stored classes\. \'puppet agent\' caches configured classes (usually at /etc/puppet/classes\.txt), and setting this option causes all of those classes to be set in your puppet manifest\.
.
.TP
\-\-logdest
Where to send messages\. Choose between syslog, the console, and a log file\. Defaults to sending messages to the console\.
.
.TP
\-\-execute
Execute a specific piece of Puppet code
.
.TP
\-\-verbose
Print extra information\.
.
.TP
\-\-apply
Apply a JSON catalog (such as one generated with \'puppet master \-\-compile\')\. You can either specify a JSON file or pipe in JSON from standard input\.
.
.SH "EXAMPLE"
.
.nf

$ puppet apply \-l /tmp/manifest\.log manifest\.pp
$ puppet apply \-\-modulepath=/root/dev/modules \-e "include ntpd::server"
.
.fi
.
.SH "AUTHOR"
Luke Kanies
.
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Labs, LLC Licensed under the Apache 2\.0 License
