.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET\-CERT" "8" "May 2018" "Puppet, Inc." "Puppet manual"
.
.SH "NAME"
\fBpuppet\-cert\fR \- Manage certificates and requests
.
.SH "SYNOPSIS"
Standalone certificate authority\. Capable of generating certificates, but mostly used for signing certificate requests from puppet clients\.
.
.SH "USAGE"
puppet cert \fIaction\fR [\-h|\-\-help] [\-V|\-\-version] [\-d|\-\-debug] [\-v|\-\-verbose] [\-\-digest \fIdigest\fR] [\fIhost\fR]
.
.SH "DESCRIPTION"
Because the puppet master service defaults to not signing client certificate requests, this script is available for signing outstanding requests\. It can be used to list outstanding requests and then either sign them individually or sign all of them\.
.
.SH "ACTIONS"
Every action except \'list\' and \'generate\' requires a hostname to act on, unless the \'\-\-all\' option is set\.
.
.P
The most important actions for day\-to\-day use are \'list\' and \'sign\'\.
.
.TP
clean
Revoke a host\'s certificate (if applicable) and remove all files related to that host from puppet cert\'s storage\. This is useful when rebuilding hosts, since new certificate signing requests will only be honored if puppet cert does not have a copy of a signed certificate for that host\. If \'\-\-all\' is specified then all host certificates, both signed and unsigned, will be removed\.
.
.TP
fingerprint
Print the DIGEST (defaults to the signing algorithm) fingerprint of a host\'s certificate\.
.
.TP
generate
Generate a certificate for a named client\. A certificate/keypair will be generated for each client named on the command line\.
.
.TP
list
List outstanding certificate requests\. If \'\-\-all\' is specified, signed certificates are also listed, prefixed by \'+\', and revoked or invalid certificates are prefixed by \'\-\' (the verification outcome is printed in parenthesis)\. If \'\-\-human\-readable\' or \'\-H\' is specified, certificates are formatted in a way to improve human scan\-ability\. If \'\-\-machine\-readable\' or \'\-m\' is specified, output is formatted concisely for consumption by a script\.
.
.TP
print
Print the full\-text version of a host\'s certificate\.
.
.TP
revoke
Revoke the certificate of a client\. The certificate can be specified either by its serial number (given as a hexadecimal number prefixed by \'0x\') or by its hostname\. The certificate is revoked by adding it to the Certificate Revocation List given by the \'cacrl\' configuration option\. Note that the puppet master needs to be restarted after revoking certificates\.
.
.TP
sign
Sign an outstanding certificate request\. If \'\-\-interactive\' or \'\-i\' is supplied the user will be prompted to confirm that they are signing the correct certificate (recommended)\. If \'\-\-assume\-yes\' or \'\-y\' is supplied the interactive prompt will assume the answer of \'yes\'\.
.
.TP
verify
Verify the named certificate against the local CA certificate\.
.
.TP
reinventory
Build an inventory of the issued certificates\. This will destroy the current inventory file specified by \'cert_inventory\' and recreate it from the certificates found in the \'certdir\'\. Ensure the puppet master is stopped before running this action\.
.
.SH "OPTIONS"
Note that any setting that\'s valid in the configuration file is also a valid long argument\. For example, \'ssldir\' is a valid setting, so you can specify \'\-\-ssldir \fIdirectory\fR\' as an argument\.
.
.P
See the configuration file documentation at https://docs\.puppetlabs\.com/puppet/latest/reference/configuration\.html for the full list of acceptable parameters\. A commented list of all configuration options can also be generated by running puppet cert with \'\-\-genconfig\'\.
.
.TP
\-\-all
Operate on all items\. Currently only makes sense with the \'sign\', \'list\', and \'fingerprint\' actions\.
.
.TP
\-\-allow\-dns\-alt\-names
Sign a certificate request even if it contains one or more alternate DNS names\. If this option isn\'t specified, \'puppet cert sign\' will ignore any requests that contain alternate names\.
.
.IP
In general, ONLY certs intended for a Puppet master server should include alternate DNS names, since Puppet agent relies on those names for identifying its rightful server\.
.
.IP
You can make Puppet agent request a certificate with alternate names by setting \'dns_alt_names\' in puppet\.conf or specifying \'\-\-dns_alt_names\' on the command line\. The output of \'puppet cert list\' shows any requested alt names for pending certificate requests\.
.
.TP
\-\-allow\-authorization\-extensions
Enable the signing of a request with authorization extensions\. Such requests are sensitive because they can be used to write access rules in Puppet Server\. Currently, this is the only means by which such requests can be signed\.
.
.TP
\-\-digest
Set the digest for fingerprinting (defaults to the digest used when signing the cert)\. Valid values depends on your openssl and openssl ruby extension version\.
.
.TP
\-\-debug
Enable full debugging\.
.
.TP
\-\-help
Print this help message
.
.TP
\-\-verbose
Enable verbosity\.
.
.TP
\-\-version
Print the puppet version number and exit\.
.
.SH "EXAMPLE"
.
.nf

$ puppet cert list
culain\.madstop\.com
$ puppet cert sign culain\.madstop\.com
.
.fi
.
.SH "AUTHOR"
Luke Kanies
.
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Inc\., LLC Licensed under the Apache 2\.0 License
