.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET\-DOC" "8" "June 2011" "Puppet Labs, LLC" "Puppet manual"
.
.SH "NAME"
\fBpuppet\-doc\fR \- Generate Puppet documentation and references
.
.SH "SYNOPSIS"
Generates a reference for all Puppet types\. Largely meant for internal Puppet Labs use\.
.
.SH "USAGE"
puppet doc [\-a|\-\-all] [\-h|\-\-help] [\-o|\-\-outputdir \fIrdoc\-outputdir\fR] [\-m|\-\-mode text|pdf|rdoc] [\-r|\-\-reference \fIreference\-name\fR] [\-\-charset \fIcharset\fR] [\fImanifest\-file\fR]
.
.SH "DESCRIPTION"
If mode is not \'rdoc\', then this command generates a Markdown document describing all installed Puppet types or all allowable arguments to puppet executables\. It is largely meant for internal use and is used to generate the reference document available on the Puppet Labs web site\.
.
.P
In \'rdoc\' mode, this command generates an html RDoc hierarchy describing the manifests that are in \'manifestdir\' and \'modulepath\' configuration directives\. The generated documentation directory is doc by default but can be changed with the \'outputdir\' option\.
.
.P
If the command is run with the name of a manifest file as an argument, puppet doc will output a single manifest\'s documentation on stdout\.
.
.SH "OPTIONS"
.
.TP
\-\-all
Output the docs for all of the reference types\. In \'rdoc\' modes, this also outputs documentation for all resources
.
.TP
\-\-help
Print this help message
.
.TP
\-\-outputdir
Specifies the directory where to output the rdoc documentation in \'rdoc\' mode\.
.
.TP
\-\-mode
Determine the output mode\. Valid modes are \'text\', \'pdf\' and \'rdoc\'\. The \'pdf\' mode creates PDF formatted files in the /tmp directory\. The default mode is \'text\'\. In \'rdoc\' mode you must provide \'manifests\-path\'
.
.TP
\-\-reference
Build a particular reference\. Get a list of references by running \'puppet doc \-\-list\'\.
.
.TP
\-\-charset
Used only in \'rdoc\' mode\. It sets the charset used in the html files produced\.
.
.SH "EXAMPLE"
.
.nf

$ puppet doc \-r type > /tmp/type_reference\.markdown
.
.fi
.
.P
or
.
.IP "" 4
.
.nf

$ puppet doc \-\-outputdir /tmp/rdoc \-\-mode rdoc /path/to/manifests
.
.fi
.
.IP "" 0
.
.P
or
.
.IP "" 4
.
.nf

$ puppet doc /etc/puppet/manifests/site\.pp
.
.fi
.
.IP "" 0
.
.P
or
.
.IP "" 4
.
.nf

$ puppet doc \-m pdf \-r configuration
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Luke Kanies
.
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Labs, LLC Licensed under the Apache 2\.0 License
