.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PUPPET\-DESCRIBE" "8" "May 2015" "Puppet Labs, LLC" "Puppet manual"
.
.SH "NAME"
\fBpuppet\-describe\fR \- Display help about resource types
.
.SH "SYNOPSIS"
Prints help about Puppet resource types, providers, and metaparameters\.
.
.SH "USAGE"
puppet describe [\-h|\-\-help] [\-s|\-\-short] [\-p|\-\-providers] [\-l|\-\-list] [\-m|\-\-meta]
.
.SH "OPTIONS"
.
.TP
\-\-help
Print this help text
.
.TP
\-\-providers
Describe providers in detail for each type
.
.TP
\-\-list
List all types
.
.TP
\-\-meta
List all metaparameters
.
.TP
\-\-short
List only parameters without detail
.
.SH "EXAMPLE"
.
.nf

$ puppet describe \-\-list
$ puppet describe file \-\-providers
$ puppet describe user \-s \-m
.
.fi
.
.SH "AUTHOR"
David Lutterkort
.
.SH "COPYRIGHT"
Copyright (c) 2011 Puppet Labs, LLC Licensed under the Apache 2\.0 License
