.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RALSH" "8" "August 2010" "" ""
Use the Puppet RAL to directly interact with the system\.puppet resource [\-h|\-\-help] [\-d|\-\-debug] [\-v|\-\-verbose] [\-e|\-\-edit]
.
.IP "" 4
.
.nf

              [\-H|\-\-host <host>] [\-p|\-\-param <param>] [\-t|\-\-types]
              type <name>
.
.fi
.
.IP "" 0
This command provides simple facilities for converting current system state into Puppet code, along with some ability to use Puppet to affect the current state\.
.
.P
By default, you must at least provide a type to list, which case puppet resource will tell you everything it knows about all instances of that type\. You can optionally specify an instance name, and puppet resource will only describe that single instance\.
.
.P
You can also add +\-\-edit+ as an argument, and puppet resource will write its output to a file, open that file in an editor, and then apply the file as a Puppet transaction\. You can easily use this to use Puppet to make simple changes to a system\.Note that any configuration parameter that\'s valid in the configuration file is also a valid long argument\. For example, \'ssldir\' is a valid configuration parameter, so you can specify \'\-\-ssldir \fIdirectory\fR\' as an argument\.
.
.P
See the configuration file documentation at http://docs\.puppetlabs\.com/references/stable/configuration\.html for the full list of acceptable parameters\. A commented list of all configuration options can also be generated by running puppet with \'\-\-genconfig\'\.
.
.P
debug: Enable full debugging\.
.
.P
edit:
.
.P
Write the results of the query to a file, open the file in an editor, and read the file back in as an executable Puppet manifest\.
.
.P
host:
.
.P
When specified, connect to the resource server on the named host and retrieve the list of resouces of the type specified\.
.
.P
help:
.
.P
Print this help message\.
.
.P
param:
.
.P
Add more parameters to be outputted from queries\.
.
.P
types:
.
.P
List all available types\.
.
.P
verbose:
.
.P
Print extra information\.This example uses \fBpuppet resource\fR to return Puppet configuration for the user \fBluke\fR:
.
.IP "" 4
.
.nf

 $ puppet resource user luke
 user { \'luke\':
   home => \'/home/luke\',
   uid => \'100\',
   ensure => \'present\',
   comment => \'Luke Kanies,,,\',
   gid => \'1000\',
   shell => \'/bin/bash\',
   groups => [\'sysadmin\',\'audio\',\'video\',\'puppet\']
 }
.
.fi
.
.IP "" 0
Luke KaniesCopyright (c) 2005\-2007 Puppet Labs, LLC Licensed under the GNU Public License
