# Specifies a gem mirror; duplicated in acceptance setup
# to ensure a similar environment on acceptance hosts.
source ENV['GEM_SOURCE'] || 'https://rubygems.org'

def location_for(place, fake_version = nil)
  if place =~ /^(git:[^#]*)#(.*)/
    [fake_version, { :git => $1, :branch => $2, :require => false }].compact
  elsif place =~ /^file:\/\/(.*)/
    ['>= 0', { :path => File.expand_path($1), :require => false }]
  else
    [place, { :require => false }]
  end
end

gem "beaker", *location_for(ENV['BEAKER_VERSION'] || '~> 3.33')
gem "beaker-puppet", *location_for(ENV['BEAKER_PUPPET_VERSION'] || "~> 0.13.4")
gem "beaker-hostgenerator", *location_for(ENV['BEAKER_HOSTGENERATOR_VERSION'] || "~> 1.1")
gem "beaker-abs", *location_for(ENV['BEAKER_ABS_VERSION'] || "~> 0.4")
gem "rake", "~> 10.1"
gem "httparty", :require => false
gem 'uuidtools', :require => false

group(:test) do
  gem "rspec", "~> 2.14.0", :require => false
  gem "mocha", "~> 0.10.5", :require => false
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
