source ENV['GEM_SOURCE'] || "https://rubygems.org"

gem "beaker", "~> 1.11.0"
gem 'rake', "~> 10.1.0"

group(:test) do
  gem "rspec", "~> 2.11.0", :require => false
  gem "mocha", "~> 0.10.5", :require => false
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
