#!/bin/sh
#

# PROVIDE: puppetmasterd
# REQUIRE: NETWORK
# KEYWORD: FreeBSD shutdown

. /etc/rc.subr

name=puppetmasterd
rcvar=`set_rcvar`

# set defaults
command=/usr/local/bin/puppetmasterd
pidfile="/var/run/$name.pid"
#required_files="/usr/local/etc/$name.conf"

# read configuration and set defaults
load_rc_config "$name"
: ${puppetmasterd_enable="NO"}
: ${puppetmasterd_config="/usr/local/etc/puppet.conf"}
: ${puppetmasterd_flags=""}

command_args="--config $puppetmasterd_config $puppetmasterd_flags"

run_rc_command "$1"
