require File.join(File.dirname(__FILE__), "spec_helper.rb")
require 'rake'
require 'spec/rake/spectask'

basedir = File.dirname(__FILE__)
puppetlibdir = File.join(basedir, "../lib")
puppettestlibdir = File.join(basedir, "../test/lib")
speclibdir = File.join(basedir, "lib")

libs = [puppetlibdir, puppettestlibdir, speclibdir]

desc "Run all spec unit tests"
Spec::Rake::SpecTask.new('unit') do |t|
    t.spec_files = FileList['unit/**/*.rb']
    t.libs = libs
    t.spec_opts = ['--options', 'spec.opts']
end

desc "Run all spec integration tests"
Spec::Rake::SpecTask.new('integration') do |t|
    t.spec_files = FileList['integration/**/*.rb']
    t.libs = libs
    t.spec_opts = ['--options', 'spec.opts']
end

desc "Run all specs"
task :all => [:unit, :integration]

task :default => [:all]
