#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.4
# from racc grammer file "grammar.ra".
#

require 'racc/parser'


require 'puppet'
require 'puppet/parser/lexer'
require 'puppet/parser/ast'
#require 'puppet/parser/interpreter'

module Puppet
    # this exception class already has a :stack accessor
    class ParseError < Puppet::Error
        attr_accessor :line, :file
    end

    class ImportError < Racc::ParseError; end
end

Puppet[:typecheck] = true
Puppet[:paramcheck] = true


module Puppet

  module Parser

    class Parser < Racc::Parser

module_eval <<'..end grammar.ra modeval..id37b4503337', 'grammar.ra', 568
attr_writer :stack
attr_reader :file

def file=(file)
    if self.stack.include?(file)
        raise Puppet::ImportError.new("Import loop detected")
    else
        @lexer.file = file
    end
end

def initialize
    @lexer = Puppet::Parser::Lexer.new()
    if Puppet[:debug]
        @yydebut = true
    end
end

def on_error(token,value,stack)
    #on '%s' at '%s' in\n'%s'" % [token,value,stack]
    #error = "line %s: parse error after '%s'" %
    #    [@lexer.line,@lexer.last]
    error = "an error was found"

    if Puppet[:debug]
        puts stack.inspect
        puts stack
    end
    if @lexer.file
        error += (" in '%s'" % @lexer.file)
    end

    except = Puppet::ParseError.new(error)
    except.line = @lexer.line
    if @lexer.file
        except.file = @lexer.file
    end

    raise except
end

# how should I do error handling here?
def parse
    begin
        yyparse(@lexer,:scan)
    rescue Racc::ParseError => except
        error = Puppet::ParseError.new(except)
        error.line = @lexer.line
        error.file = @lexer.file
        error.stack = caller
        raise error
    rescue Puppet::ParseError => except
        except.line ||= @lexer.line
        except.file ||= @lexer.file
        raise except
    rescue Puppet::Error => except
        # and this is a framework error
        except.line ||= @lexer.line
        except.file ||= @lexer.file
        except.stack ||= except.stack
        if Puppet[:debug]
            puts except.stack
        end
        raise except
    rescue Puppet::DevError => except
        except.line ||= @lexer.line
        except.file ||= @lexer.file
        except.stack ||= caller
        if Puppet[:debug]
            puts except.stack
        end
        raise except
    rescue => except
        error = Puppet::DevError.new(except.message)
        error.line = @lexer.line
        error.file = @lexer.file
        error.stack = caller
        if Puppet[:debug]
            puts caller
        end
        raise error
    end
end

def stack
    if defined? @stack and ! @stack.nil?
        if @lexer.file
            return [@stack,@lexer.file].flatten
        else
            return @stack
        end
    else
        if @lexer.file
            return [@lexer.file]
        else
            return []
        end
    end
end

def string=(string)
    @lexer.string = string
end
..end grammar.ra modeval..id37b4503337

##### racc 1.4.4 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 40, :_reduce_1,
 1, 41, :_reduce_none,
 2, 41, :_reduce_3,
 1, 42, :_reduce_none,
 1, 42, :_reduce_none,
 1, 42, :_reduce_none,
 1, 42, :_reduce_none,
 1, 42, :_reduce_none,
 1, 42, :_reduce_none,
 5, 43, :_reduce_10,
 5, 43, :_reduce_11,
 5, 43, :_reduce_12,
 3, 55, :_reduce_13,
 1, 50, :_reduce_none,
 3, 50, :_reduce_15,
 0, 51, :_reduce_none,
 1, 51, :_reduce_none,
 1, 49, :_reduce_18,
 1, 54, :_reduce_19,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 1, 56, :_reduce_none,
 3, 44, :_reduce_25,
 0, 52, :_reduce_26,
 1, 52, :_reduce_27,
 3, 52, :_reduce_28,
 3, 62, :_reduce_29,
 1, 63, :_reduce_none,
 3, 63, :_reduce_31,
 1, 61, :_reduce_none,
 1, 61, :_reduce_none,
 1, 61, :_reduce_none,
 1, 61, :_reduce_none,
 1, 61, :_reduce_none,
 1, 61, :_reduce_none,
 1, 61, :_reduce_none,
 1, 61, :_reduce_none,
 1, 61, :_reduce_none,
 1, 57, :_reduce_41,
 1, 65, :_reduce_42,
 4, 66, :_reduce_43,
 5, 45, :_reduce_44,
 1, 67, :_reduce_none,
 2, 67, :_reduce_46,
 5, 68, :_reduce_47,
 1, 69, :_reduce_none,
 3, 69, :_reduce_49,
 3, 58, :_reduce_50,
 1, 71, :_reduce_none,
 3, 71, :_reduce_52,
 1, 73, :_reduce_none,
 3, 73, :_reduce_54,
 3, 72, :_reduce_55,
 1, 70, :_reduce_56,
 1, 70, :_reduce_57,
 1, 70, :_reduce_58,
 1, 70, :_reduce_59,
 1, 70, :_reduce_none,
 2, 46, :_reduce_61,
 6, 47, :_reduce_62,
 7, 48, :_reduce_63,
 0, 76, :_reduce_64,
 1, 74, :_reduce_none,
 3, 74, :_reduce_66,
 3, 74, :_reduce_67,
 1, 77, :_reduce_none,
 3, 77, :_reduce_69,
 3, 78, :_reduce_70,
 1, 78, :_reduce_71,
 1, 75, :_reduce_none,
 2, 75, :_reduce_73,
 1, 59, :_reduce_74,
 3, 60, :_reduce_75,
 1, 64, :_reduce_none,
 1, 64, :_reduce_none,
 0, 53, :_reduce_none,
 1, 53, :_reduce_79 ]

racc_reduce_n = 80

racc_shift_n = 135

racc_action_table = [
    76,    99,    79,   111,    48,    76,    90,    98,     4,     7,
    76,    11,    13,   109,   125,    76,    71,    72,     2,     5,
    76,     9,    92,    47,    94,    76,    36,   110,    31,    22,
    24,    74,    75,    31,    89,    78,    74,    75,    31,    92,
    78,    74,    75,    31,    89,    78,    74,    75,    31,   100,
    78,    74,    75,    31,    27,    78,    74,    75,    31,   101,
    78,     2,     5,    22,    24,    22,    24,    70,    22,    24,
     5,    71,    72,    63,    22,    24,   104,    22,    24,    22,
    24,    62,   107,    41,    22,    24,    40,    63,    27,    46,
    27,    88,    31,    27,    31,     2,     5,     2,     5,    27,
   115,    53,    27,    31,    27,   134,     2,     5,    31,    27,
     5,     2,     5,    31,    22,    24,     2,     5,    63,    22,
    24,   117,    46,     4,     7,   119,    11,    13,   120,     5,
    41,    40,    38,     2,     5,   123,     9,    69,   127,    27,
   133,    37,   129,    31,    27,    36,     2,     5,    31,    35,
    20,     2,     5,     4,     7,    63,    11,    13,     4,     7,
    19,    11,    13,     2,     5,   118,     9,   nil,     2,     5,
   nil,     9,     4,     7,   nil,    11,    13,     4,     7,   nil,
    11,    13,     2,     5,   nil,     9,   nil,     2,     5,   nil,
     9,     4,     7,   nil,    11,    13,     4,     7,   nil,    11,
    13,     2,     5,   nil,     9,   nil,     2,     5,   nil,     9 ]

racc_action_check = [
    46,    65,    46,    86,    30,    48,    58,    65,   119,   119,
    84,   119,   119,    84,   106,   111,   106,   106,   119,   119,
   126,   119,    60,    29,    61,    79,    29,    86,    46,   104,
   104,    46,    46,    48,    63,    46,    48,    48,    84,    64,
    48,    84,    84,   111,    53,    84,   111,   111,   126,    67,
   111,   126,   126,    79,   104,   126,    79,    79,   104,    68,
    79,   104,   104,     9,     9,    73,    73,    45,    36,    36,
    41,    45,    45,    40,   100,   100,    77,    90,    90,    22,
    22,    38,    83,    37,    35,    35,    34,    88,     9,    55,
    73,    51,     9,    36,    73,     9,     9,    73,    73,   100,
    91,    36,    90,   100,    22,   132,   100,   100,    22,    35,
    90,    22,    22,    35,    89,    89,    35,    35,    92,    47,
    47,    93,    26,   132,   132,    95,   132,   132,    97,    99,
    20,    17,    14,   132,   132,   102,   132,    42,   110,    89,
   130,    13,   112,    89,    47,    12,    89,    89,    47,    11,
     7,    47,    47,   102,   102,   129,   102,   102,   130,   130,
     4,   130,   130,   102,   102,    94,   102,   nil,   130,   130,
   nil,   130,    69,    69,   nil,    69,    69,    15,    15,   nil,
    15,    15,    69,    69,   nil,    69,   nil,    15,    15,   nil,
    15,   127,   127,   nil,   127,   127,     0,     0,   nil,     0,
     0,   127,   127,   nil,   127,   nil,     0,     0,   nil,     0 ]

racc_action_pointer = [
   172,   nil,   nil,   nil,   157,   nil,   nil,   115,   nil,    61,
   nil,   137,   140,   106,   132,   153,   nil,   126,   nil,   nil,
   116,   nil,    77,   nil,   nil,   nil,   109,   nil,   nil,    21,
    -1,   nil,   nil,   nil,    81,    82,    66,    69,    81,   nil,
    38,    35,   132,   nil,   nil,    63,    -3,   117,     2,   nil,
   nil,    58,   nil,    36,   nil,    76,   nil,   nil,   -30,   nil,
    13,    -5,   nil,    26,    30,    -8,   nil,    37,    44,   148,
   nil,   nil,   nil,    63,   nil,   nil,   nil,    68,   nil,    22,
   nil,   nil,   nil,    78,     7,   nil,    -6,   nil,    52,   112,
    75,    94,    83,   115,   130,   120,   nil,   122,   nil,    94,
    72,   nil,   129,   nil,    27,   nil,     8,   nil,   nil,   nil,
   133,    12,   133,   nil,   nil,   nil,   nil,   nil,   nil,   -16,
   nil,   nil,   nil,   nil,   nil,   nil,    17,   167,   nil,   120,
   134,   nil,    99,   nil,   nil ]

racc_action_default = [
   -80,    -5,   -19,    -6,   -80,   -18,    -7,   -80,    -8,   -80,
    -9,   -80,   -80,   -80,   -80,    -1,    -2,   -80,    -4,   -61,
   -64,   -40,   -80,   -32,   -41,   -36,   -38,   -74,   -39,   -33,
   -80,   -42,   -37,   -35,   -34,   -80,   -26,   -64,   -80,    -3,
   -26,   -64,   -80,   -65,   -30,   -80,   -80,   -80,   -80,   -25,
   -14,   -80,   -20,   -18,   -22,   -23,   -24,   -21,   -16,   -27,
   -78,   -64,   135,   -80,   -78,   -80,   -68,   -71,   -80,   -80,
   -75,   -76,   -77,   -80,   -57,   -56,   -58,   -80,   -59,   -80,
   -50,   -51,   -60,   -80,   -80,   -45,   -80,   -48,   -26,   -80,
   -17,   -80,   -79,   -80,   -80,   -80,   -72,   -80,   -67,   -80,
   -80,   -66,   -80,   -31,   -80,   -53,   -80,   -43,   -46,   -44,
   -80,   -80,   -13,   -29,   -15,   -10,   -28,   -11,   -73,   -80,
   -12,   -69,   -70,   -62,   -55,   -52,   -80,   -80,   -49,   -80,
   -80,   -54,   -80,   -63,   -47 ]

racc_goto_table = [
    15,    39,    30,    32,    73,    66,    81,    87,    52,    60,
    29,    85,    34,    64,    54,    44,    32,    55,    50,    82,
   106,    82,   116,    29,    56,    34,    68,    42,    49,    32,
    93,    80,    58,    91,    97,    45,    29,    57,    34,   105,
    83,    32,    67,    87,    61,    95,    96,   108,    29,    84,
    34,    65,    82,    14,   nil,   nil,   nil,    82,   nil,   116,
   nil,   112,    52,   121,   nil,   126,   103,    32,    54,   102,
   128,    55,   114,   nil,    29,   nil,    34,   nil,    56,   nil,
   nil,   nil,   113,    32,    82,   nil,   131,   nil,    39,   nil,
    29,    57,    34,   122,    32,   nil,   nil,   124,    32,    82,
    67,    29,   nil,    34,   nil,    29,   nil,    34,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    39,   nil,    39,   130,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   132 ]

racc_goto_check = [
     2,     3,    22,     4,    25,    39,    33,    31,    18,    13,
    10,    29,    15,    13,    19,    22,     4,    20,    16,    26,
    34,    26,    23,    10,    21,    15,    37,    35,    22,     4,
    14,    32,    11,    12,    14,    24,    10,    10,    15,    33,
    22,     4,    10,    31,    35,    36,    37,    29,    10,    28,
    15,    38,    26,     1,   nil,   nil,   nil,    26,   nil,    23,
   nil,    13,    18,    39,   nil,    25,    22,     4,    19,     2,
    31,    20,    16,   nil,    10,   nil,    15,   nil,    21,   nil,
   nil,   nil,    22,     4,    26,   nil,    33,   nil,     3,   nil,
    10,    10,    15,    22,     4,   nil,   nil,    22,     4,    26,
    10,    10,   nil,    15,   nil,    10,   nil,    15,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,     3,     2,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,    53,     0,   -14,    -6,   nil,   nil,   nil,   nil,   nil,
     1,    -4,   -25,   -27,   -30,     3,   -18,   nil,   -28,   -22,
   -19,   -12,    -7,   -70,    13,   -41,   -27,   nil,     1,   -37,
   nil,   -41,   -15,   -40,   -59,     7,   -16,   -15,    10,   -36 ]

racc_goto_default = [
   nil,   nil,   nil,    16,    18,     1,     3,     6,     8,    10,
    12,   nil,   nil,   nil,   nil,    17,   nil,    51,    23,    25,
    26,    28,   nil,    59,   nil,   nil,    33,    21,   nil,   nil,
    86,    77,   nil,   nil,   nil,   nil,   nil,    43,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :LBRACK => 2,
 :QTEXT => 3,
 :RBRACK => 4,
 :LBRACE => 5,
 :RBRACE => 6,
 :SYMBOL => 7,
 :FARROW => 8,
 :COMMA => 9,
 :TRUE => 10,
 :FALSE => 11,
 :EQUALS => 12,
 :QMARK => 13,
 :LPAREN => 14,
 :RPAREN => 15,
 :ISEQUAL => 16,
 :GREATEREQUAL => 17,
 :GREATERTHAN => 18,
 :LESSTHAN => 19,
 :LESSEQUAL => 20,
 :NOTEQUAL => 21,
 :IF => 22,
 :ELSE => 23,
 :IMPORT => 24,
 :DEFINE => 25,
 :ELSIF => 26,
 :VARIABLE => 27,
 :CLASS => 28,
 :INHERITS => 29,
 :NODE => 30,
 :BOOLEAN => 31,
 :DOT => 32,
 :COLON => 33,
 :TYPE => 34,
 :NAME => 35,
 :SEMIC => 36,
 :CASE => 37,
 :DEFAULT => 38 }

racc_use_result_var = true

racc_nt_base = 39

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'LBRACK',
'QTEXT',
'RBRACK',
'LBRACE',
'RBRACE',
'SYMBOL',
'FARROW',
'COMMA',
'TRUE',
'FALSE',
'EQUALS',
'QMARK',
'LPAREN',
'RPAREN',
'ISEQUAL',
'GREATEREQUAL',
'GREATERTHAN',
'LESSTHAN',
'LESSEQUAL',
'NOTEQUAL',
'IF',
'ELSE',
'IMPORT',
'DEFINE',
'ELSIF',
'VARIABLE',
'CLASS',
'INHERITS',
'NODE',
'BOOLEAN',
'DOT',
'COLON',
'TYPE',
'NAME',
'SEMIC',
'CASE',
'DEFAULT',
'$start',
'program',
'statements',
'statement',
'object',
'assignment',
'casestatement',
'import',
'definition',
'hostclass',
'name',
'objectinstances',
'endsemi',
'params',
'endcomma',
'type',
'objectinst',
'objectname',
'quotedtext',
'selector',
'variable',
'array',
'rvalue',
'param',
'rvalues',
'comma',
'boolean',
'objectref',
'caseopts',
'caseopt',
'casevalues',
'selectlhand',
'svalues',
'selectval',
'sintvalues',
'argumentlist',
'parent',
'nothing',
'arguments',
'argument']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'grammar.ra', 40
  def _reduce_1( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :children => [val[0]]
        )
    end

    # this is mainly so we can test the parser separately from the
    # interpreter
    if Puppet[:parseonly]
        begin
            if Puppet[:debug]
                puts result.tree(0)
            end
        rescue NoMethodError => detail
            Puppet.err detail
            #exit(78)
        end
        #require 'puppet/parser/interpreter'
        #result = Puppet::Server.new(result)
    end
   result
  end
.,.,

 # reduce 2 omitted

module_eval <<'.,.,', 'grammar.ra', 54
  def _reduce_3( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[1])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :file => @lexer.file,
            :line => @lexer.line,
            :children => [val[0],val[1]]
        )
    end
   result
  end
.,.,

 # reduce 4 omitted

 # reduce 5 omitted

 # reduce 6 omitted

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

module_eval <<'.,.,', 'grammar.ra', 93
  def _reduce_10( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        raise Puppet::ParseError, "Invalid name"
    end
    array = val[2]
    if array.is_a?(AST::ObjectInst)
        array = [array]
    end
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file
    )
    # this iterates across each specified objectinstance
    array.each { |instance|
        unless instance.is_a?(AST::ObjectInst)
            raise Puppet::Dev, "Got something that isn't an instance"
        end
        # now, i need to somehow differentiate between those things with
        # arrays in their names, and normal things
        result.push AST::ObjectDef.new(
            :pin => "{}",
            :line => @lexer.line,
            :file => @lexer.file,
            :type => val[0],
            :name => instance[0],
            :params => instance[1]
        )
    }
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 116
  def _reduce_11( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        Puppet.notice "invalid name"
        raise Puppet::ParseError, "Invalid name"
    end
    # an object but without a name
    # this cannot be an instance of a library type

    # make a unique name for bookkeeping purposes
    name = AST::Name.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => [val[0].value, "-", val[0].object_id].join('')
    )

    result = AST::ObjectDef.new(
        :pin => "{}",
        :line => @lexer.line,
        :file => @lexer.file,
        :type => val[0],
        :name => name,
        :params => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 129
  def _reduce_12( val, _values, result )
    # a template setting for a type
    if val[0].is_a?(AST::ASTArray)
        Puppet.notice "invalid type"
        raise Puppet::ParseError, "Invalid type"
    end
    result = AST::TypeDefaults.new(
        :pin => "{}",
        :line => @lexer.line,
        :file => @lexer.file,
        :type => val[0],
        :params => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 137
  def _reduce_13( val, _values, result )
    result = AST::ObjectInst.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => [val[0],val[2]]
    )
   result
  end
.,.,

 # reduce 14 omitted

module_eval <<'.,.,', 'grammar.ra', 151
  def _reduce_15( val, _values, result )
    if val[0].is_a?(AST::ObjectInst)
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    else
        val[0].push val[2]
        result = val[0]
    end
   result
  end
.,.,

 # reduce 16 omitted

 # reduce 17 omitted

module_eval <<'.,.,', 'grammar.ra', 162
  def _reduce_18( val, _values, result )
    result = AST::Name.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 170
  def _reduce_19( val, _values, result )
    result = AST::Type.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

 # reduce 20 omitted

 # reduce 21 omitted

 # reduce 22 omitted

 # reduce 23 omitted

 # reduce 24 omitted

module_eval <<'.,.,', 'grammar.ra', 192
  def _reduce_25( val, _values, result )
    # this is distinct from referencing a variable
    variable = AST::Name.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0].sub(/^\$/,'')
    )
    result = AST::VarDef.new(
        :pin => "=",
        :line => @lexer.line,
        :file => @lexer.file,
        :name => variable,
        :value => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 201
  def _reduce_26( val, _values, result )
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => []
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 201
  def _reduce_27( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 214
  def _reduce_28( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[2])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 229
  def _reduce_29( val, _values, result )
    leaf = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
    result = AST::ObjectParam.new(
        :pin => "=>",
        :line => @lexer.line,
        :file => @lexer.file,
        :param => leaf,
        :value => val[2]
    )
   result
  end
.,.,

 # reduce 30 omitted

module_eval <<'.,.,', 'grammar.ra', 242
  def _reduce_31( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        result = val[0].push(val[2])
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

 # reduce 32 omitted

 # reduce 33 omitted

 # reduce 34 omitted

 # reduce 35 omitted

 # reduce 36 omitted

 # reduce 37 omitted

 # reduce 38 omitted

 # reduce 39 omitted

 # reduce 40 omitted

module_eval <<'.,.,', 'grammar.ra', 260
  def _reduce_41( val, _values, result )
    result = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 268
  def _reduce_42( val, _values, result )
    result = AST::Boolean.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 278
  def _reduce_43( val, _values, result )
    result = AST::ObjectRef.new(
        :pin => '[]',
        :line => @lexer.line,
        :file => @lexer.file,
        :type => val[0],
        :name => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 295
  def _reduce_44( val, _values, result )
    options = val[3]
    unless options.is_a?(AST::ASTArray)
        options = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[3]]
        )
    end
    result = AST::CaseStatement.new(
        :test => val[1],
        :options => val[3],
        :file => @lexer.file,
        :line => @lexer.line
    )
   result
  end
.,.,

 # reduce 45 omitted

module_eval <<'.,.,', 'grammar.ra', 309
  def _reduce_46( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push val[1]
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0], val[1]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 319
  def _reduce_47( val, _values, result )
    result = AST::CaseOpt.new(
        :pin => ":",
        :value => val[0],
        :file => @lexer.file,
        :line => @lexer.line,
        :statements => val[3]
    )
   result
  end
.,.,

 # reduce 48 omitted

module_eval <<'.,.,', 'grammar.ra', 333
  def _reduce_49( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[2])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 343
  def _reduce_50( val, _values, result )
    result = AST::Selector.new(
        :pin => "?",
        :line => @lexer.line,
        :file => @lexer.file,
        :param => val[0],
        :value => val[2]
    )
   result
  end
.,.,

 # reduce 51 omitted

module_eval <<'.,.,', 'grammar.ra', 345
  def _reduce_52( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 53 omitted

module_eval <<'.,.,', 'grammar.ra', 360
  def _reduce_54( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[2])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 370
  def _reduce_55( val, _values, result )
    result = AST::ObjectParam.new(
        :pin => "=>",
        :line => @lexer.line,
        :file => @lexer.file,
        :param => val[0],
        :value => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 378
  def _reduce_56( val, _values, result )
    result = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 385
  def _reduce_57( val, _values, result )
    result = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 392
  def _reduce_58( val, _values, result )
    result = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 399
  def _reduce_59( val, _values, result )
    result = AST::Default.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

 # reduce 60 omitted

module_eval <<'.,.,', 'grammar.ra', 432
  def _reduce_61( val, _values, result )
    # importing files
    # yuk, i hate keywords
    # we'll probably have to have some kind of search path eventually
    # but for now, just use a path relative to the file doing the importing
    dir = @lexer.file.sub(%r{[^/]+$},'').sub(/\/$/, '')
    if dir == ""
        dir = "."
    end
    Dir.chdir(dir) {
        Dir.glob(val[1]).each { |file|
            parser = Puppet::Parser::Parser.new()
            parser.stack = self.stack
            Puppet.debug("importing '%s'" % file)
            begin
                parser.file = file
            rescue Puppet::ImportError
                Puppet.warning(
                    "Importing %s would result in an import loop" %
                        File.join(dir, file)
                )
                result = AST::ASTArray.new(
                    :file => @lexer.file,
                    :line => @lexer.line
                )
                next
            end
            result = parser.parse
        }
    }
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 442
  def _reduce_62( val, _values, result )
    result = AST::CompDef.new(
        :name => AST::Name.new(:value => val[1], :line => @lexer.line),
        :args => val[2],
        :file => @lexer.file,
        :line => @lexer.line,
        :code => val[4]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 453
  def _reduce_63( val, _values, result )
    result = AST::ClassDef.new(
        :name => AST::Name.new(:value => val[1], :line => @lexer.line),
        :args => val[2],
        :parentclass => val[3],
        :file => @lexer.file,
        :line => @lexer.line,
        :code => val[5]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 468
  def _reduce_64( val, _values, result )
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => []
    )
   result
  end
.,.,

 # reduce 65 omitted

module_eval <<'.,.,', 'grammar.ra', 473
  def _reduce_66( val, _values, result )
    result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 484
  def _reduce_67( val, _values, result )
    if val[1].is_a?(AST::ASTArray)
        result = val[1]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0]]
        )
    end
   result
  end
.,.,

 # reduce 68 omitted

module_eval <<'.,.,', 'grammar.ra', 498
  def _reduce_69( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[2])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 506
  def _reduce_70( val, _values, result )
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => [val[0],val[2]]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 513
  def _reduce_71( val, _values, result )
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => [val[0]]
    )
   result
  end
.,.,

 # reduce 72 omitted

module_eval <<'.,.,', 'grammar.ra', 522
  def _reduce_73( val, _values, result )
    result = AST::Name.new(
        :value => val[1],
        :file => @lexer.file,
        :line => @lexer.line
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 531
  def _reduce_74( val, _values, result )
    name = val[0].sub(/^\$/,'')
    result = AST::Variable.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => name
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 540
  def _reduce_75( val, _values, result )
    if val[1].is_a?(AST::ASTArray)
        result = val[1]
    else
        result = AST::ASTArray.new
        result.push val[1]
    end
   result
  end
.,.,

 # reduce 76 omitted

 # reduce 77 omitted

 # reduce 78 omitted

module_eval <<'.,.,', 'grammar.ra', 545
  def _reduce_79( val, _values, result )
 result = nil
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

    end   # class Parser

  end   # module Parser

end   # module Puppet
