#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.4
# from racc grammer file "grammar.ra".
#

require 'racc/parser'


require 'puppet'
require 'puppet/parsedfile'
require 'puppet/parser/lexer'
require 'puppet/parser/ast'
#require 'puppet/parser/interpreter'

module Puppet
    # this exception class already has a :stack accessor
    class ParseError < Puppet::Error
        attr_accessor :line, :file
    end

    class ImportError < Racc::ParseError; end
end

Puppet[:typecheck] = true
Puppet[:paramcheck] = true


module Puppet

  module Parser

    class Parser < Racc::Parser

module_eval <<'..end grammar.ra modeval..id9e2c7fc335', 'grammar.ra', 638
attr_reader :file, :files

# Create an AST array out of all of the args
def aryfy(*args)
    if args[0].is_a?(AST::ASTArray)
        result = args.shift
        args.each { |arg|
            args.push arg
        }
    else
        result = AST::ASTArray.new(
            :children => args
        )
    end

    return result
end

def file=(file)
    unless FileTest.exists?(file)
        raise Puppet::Error, "Could not find file %s" % file
    end
    if @files.detect { |f| f.file == file }
        raise Puppet::ImportError.new("Import loop detected")
    else
        @files << Puppet::ParsedFile.new(file)
        @lexer.file = file
    end
end

def initialize
    @lexer = Puppet::Parser::Lexer.new()
    @files = []
    #if Puppet[:debug]
    #    @yydebug = true
    #end
end

def on_error(token,value,stack)
    #on '%s' at '%s' in\n'%s'" % [token,value,stack]
    #error = "line %s: parse error after '%s'" %
    #    [@lexer.line,@lexer.last]
    error = "Syntax error at '%s'" % [value]

    #if Puppet[:debug]
        #puts stack.inspect
        #puts stack.class
    #end
    #if @lexer.file
    #    error += (" in '%s'" % @lexer.file)
    #end

    except = Puppet::ParseError.new(error)
    except.line = @lexer.line
    if @lexer.file
        except.file = @lexer.file
    end

    raise except
end

# how should I do error handling here?
def parse
    begin
        yyparse(@lexer,:scan)
    rescue Racc::ParseError => except
        error = Puppet::ParseError.new(except)
        error.line = @lexer.line
        error.file = @lexer.file
        error.stack = caller
        raise error
    rescue Puppet::ParseError => except
        except.line ||= @lexer.line
        except.file ||= @lexer.file
        raise except
    rescue Puppet::Error => except
        # and this is a framework error
        except.line ||= @lexer.line
        except.file ||= @lexer.file
        except.stack ||= except.stack
        #if Puppet[:debug]
        #    puts except.stack
        #end
        raise except
    rescue Puppet::DevError => except
        except.line ||= @lexer.line
        except.file ||= @lexer.file
        except.stack ||= caller
        #if Puppet[:debug]
        #    puts except.stack
        #end
        raise except
    rescue => except
        error = Puppet::DevError.new(except.message)
        error.line = @lexer.line
        error.file = @lexer.file
        error.stack = caller
        #if Puppet[:debug]
        #    puts caller
        #end
        raise error
    end
end

def reparse?
    return @files.detect { |file| file.changed? }
end

def string=(string)
    @lexer.string = string
end
..end grammar.ra modeval..id9e2c7fc335

##### racc 1.4.4 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 41, :_reduce_1,
 1, 42, :_reduce_none,
 2, 42, :_reduce_3,
 1, 43, :_reduce_none,
 1, 43, :_reduce_none,
 1, 43, :_reduce_none,
 1, 43, :_reduce_none,
 1, 43, :_reduce_none,
 1, 43, :_reduce_none,
 1, 43, :_reduce_none,
 1, 43, :_reduce_none,
 2, 48, :_reduce_12,
 1, 52, :_reduce_none,
 3, 52, :_reduce_14,
 1, 53, :_reduce_none,
 1, 53, :_reduce_none,
 5, 44, :_reduce_17,
 5, 44, :_reduce_18,
 5, 44, :_reduce_19,
 3, 61, :_reduce_20,
 1, 56, :_reduce_none,
 3, 56, :_reduce_22,
 0, 57, :_reduce_none,
 1, 57, :_reduce_none,
 1, 54, :_reduce_25,
 1, 60, :_reduce_26,
 1, 62, :_reduce_none,
 1, 62, :_reduce_none,
 1, 62, :_reduce_none,
 1, 62, :_reduce_none,
 1, 62, :_reduce_none,
 1, 62, :_reduce_none,
 3, 45, :_reduce_33,
 0, 58, :_reduce_34,
 1, 58, :_reduce_35,
 3, 58, :_reduce_36,
 3, 67, :_reduce_37,
 1, 68, :_reduce_none,
 3, 68, :_reduce_39,
 1, 66, :_reduce_none,
 1, 66, :_reduce_none,
 1, 66, :_reduce_none,
 1, 66, :_reduce_none,
 1, 66, :_reduce_none,
 1, 66, :_reduce_none,
 1, 66, :_reduce_none,
 1, 66, :_reduce_none,
 1, 66, :_reduce_none,
 1, 63, :_reduce_49,
 1, 70, :_reduce_50,
 4, 71, :_reduce_51,
 5, 46, :_reduce_52,
 1, 72, :_reduce_none,
 2, 72, :_reduce_54,
 5, 73, :_reduce_55,
 1, 74, :_reduce_none,
 3, 74, :_reduce_57,
 3, 64, :_reduce_58,
 1, 76, :_reduce_none,
 3, 76, :_reduce_60,
 1, 78, :_reduce_none,
 3, 78, :_reduce_62,
 3, 77, :_reduce_63,
 1, 75, :_reduce_64,
 1, 75, :_reduce_65,
 1, 75, :_reduce_66,
 1, 75, :_reduce_67,
 1, 75, :_reduce_none,
 2, 47, :_reduce_69,
 6, 49, :_reduce_70,
 6, 50, :_reduce_71,
 5, 51, :_reduce_72,
 1, 81, :_reduce_none,
 2, 81, :_reduce_74,
 0, 82, :_reduce_75,
 1, 79, :_reduce_none,
 3, 79, :_reduce_77,
 3, 79, :_reduce_78,
 1, 83, :_reduce_none,
 3, 83, :_reduce_80,
 3, 84, :_reduce_81,
 1, 84, :_reduce_82,
 1, 80, :_reduce_none,
 2, 80, :_reduce_84,
 1, 55, :_reduce_85,
 3, 65, :_reduce_86,
 1, 69, :_reduce_none,
 1, 69, :_reduce_none,
 0, 59, :_reduce_none,
 1, 59, :_reduce_90 ]

racc_reduce_n = 91

racc_shift_n = 151

racc_action_table = [
    88,   123,    88,   118,    96,    31,    31,    52,    88,   117,
    88,   120,   107,     5,     5,   100,    88,   106,    88,   101,
   102,    55,   112,    58,    67,   122,    50,   104,    35,   106,
    35,    86,    87,    86,    87,    90,    35,    90,    35,    86,
    87,    86,    87,    90,    35,    90,    35,    86,    87,    86,
    87,    90,   133,    90,     5,   144,   114,   101,   102,   104,
   116,    40,   119,    55,    54,   108,   126,    50,   138,   128,
     4,     7,    61,    11,    14,   130,    18,    28,    29,    61,
     2,     5,    66,     9,    48,    15,     4,     7,   134,    11,
    14,     5,    18,    28,    29,   136,     2,     5,    61,     9,
     5,    15,    31,    28,    29,    28,    29,     5,    41,     2,
     5,   141,    40,    81,    28,    29,    28,    29,    31,    39,
    24,   147,    35,    65,    23,     2,     5,    61,    31,    69,
    31,   nil,    35,   146,    35,     2,     5,     2,     5,    31,
   nil,    31,   nil,    35,    28,    29,     2,     5,     2,    72,
   nil,     4,     7,   nil,    11,    14,   nil,    18,    28,    29,
   nil,     2,     5,   nil,     9,   nil,    15,   nil,   nil,    31,
   nil,   nil,   nil,    35,   150,   nil,     2,     5,   nil,    28,
    29,    28,    29,    31,   nil,   nil,   nil,    35,   nil,   nil,
     2,     5,     4,     7,   nil,    11,    14,   nil,    18,   nil,
   nil,   nil,     2,     5,    31,     9,    31,    15,    35,   nil,
    35,     2,     5,     2,     5,     4,     7,   nil,    11,    14,
   nil,    18,   nil,   nil,   nil,     2,     5,   nil,     9,   nil,
    15,     4,     7,   nil,    11,    14,   nil,    18,   nil,   nil,
   nil,     2,     5,   nil,     9,   nil,    15,     4,     7,   nil,
    11,    14,   nil,    18,   nil,   nil,   nil,     2,     5,   nil,
     9,   nil,    15,     4,     7,   nil,    11,    14,   nil,    18,
   nil,   nil,   nil,     2,     5,   nil,     9,   nil,    15,     4,
     7,   nil,    11,    14,   nil,    18,   nil,   nil,   nil,     2,
     5,   nil,     9,   nil,    15,     4,     7,   nil,    11,    14,
   nil,    18,   nil,   nil,   nil,     2,     5,   nil,     9,   nil,
    15 ]

racc_action_check = [
   143,    93,    55,    83,    55,    15,    66,    24,    91,    83,
    96,    91,    63,    15,    66,    57,    54,    62,   123,    57,
    57,    70,    71,    38,    46,    93,    38,    72,   143,    73,
    55,   143,   143,    55,    55,   143,    91,    55,    96,    91,
    91,    96,    96,    91,    54,    96,   123,    54,    54,   123,
   123,    54,   110,   123,    46,   125,    76,   125,   125,    61,
    82,    33,    85,    26,    25,    65,    97,    21,   115,   103,
   110,   110,    40,   110,   110,   105,   110,   112,   112,   106,
   110,   110,    43,   110,    19,   110,   115,   115,   111,   115,
   115,    18,   115,   119,   119,   113,   115,   115,   114,   115,
    52,   115,   112,   104,   104,   126,   126,   118,    14,   112,
   112,   122,    12,    51,     9,     9,    50,    50,   119,    11,
     7,   137,   119,    41,     4,   119,   119,   147,   104,    48,
   126,   nil,   104,   132,   126,   104,   104,   126,   126,     9,
   nil,    50,   nil,     9,    28,    28,     9,     9,    50,    50,
   nil,   132,   132,   nil,   132,   132,   nil,   132,    58,    58,
   nil,   132,   132,   nil,   132,   nil,   132,   nil,   nil,    28,
   nil,   nil,   nil,    28,   148,   nil,    28,    28,   nil,    39,
    39,    99,    99,    58,   nil,   nil,   nil,    58,   nil,   nil,
    58,    58,   148,   148,   nil,   148,   148,   nil,   148,   nil,
   nil,   nil,   148,   148,    39,   148,    99,   148,    39,   nil,
    99,    39,    39,    99,    99,   107,   107,   nil,   107,   107,
   nil,   107,   nil,   nil,   nil,   107,   107,   nil,   107,   nil,
   107,     0,     0,   nil,     0,     0,   nil,     0,   nil,   nil,
   nil,     0,     0,   nil,     0,   nil,     0,   141,   141,   nil,
   141,   141,   nil,   141,   nil,   nil,   nil,   141,   141,   nil,
   141,   nil,   141,    67,    67,   nil,    67,    67,   nil,    67,
   nil,   nil,   nil,    67,    67,   nil,    67,   nil,    67,    20,
    20,   nil,    20,    20,   nil,    20,   nil,   nil,   nil,    20,
    20,   nil,    20,   nil,    20,    81,    81,   nil,    81,    81,
   nil,    81,   nil,   nil,   nil,    81,    81,   nil,    81,   nil,
    81 ]

racc_action_pointer = [
   207,   nil,   nil,   nil,   121,   nil,   nil,    85,   nil,   112,
   nil,   107,   107,   nil,    73,   -22,   nil,   nil,    56,    84,
   255,    62,   nil,   nil,    -7,    59,    50,   nil,   142,   nil,
   nil,   nil,   nil,    56,   nil,   nil,   nil,   nil,    21,   177,
    37,    94,   nil,    73,   nil,   nil,    19,   nil,   129,   nil,
   114,   108,    65,   nil,    13,    -1,   nil,    11,   156,   nil,
   nil,    51,     8,     7,   nil,    30,   -21,   239,   nil,   nil,
     8,   -14,    19,    20,   nil,   nil,    23,   nil,   nil,   nil,
   nil,   271,    45,    -6,   nil,    50,   nil,   nil,   nil,   nil,
   nil,     5,   nil,    -8,   nil,   nil,     7,    58,   nil,   179,
   nil,   nil,   nil,    65,   101,    69,    44,   191,   nil,   nil,
    46,    82,    75,    89,    63,    62,   nil,   nil,    72,    91,
   nil,   nil,   106,    15,   nil,    49,   103,   nil,   nil,   nil,
   nil,   nil,   127,   nil,   nil,   nil,   nil,   112,   nil,   nil,
   nil,   223,   nil,    -3,   nil,   nil,   nil,    92,   168,   nil,
   nil ]

racc_action_default = [
   -91,    -4,   -26,    -5,   -91,   -25,    -6,   -91,    -7,   -91,
    -8,   -91,   -91,    -9,   -91,   -91,   -10,   -11,   -91,   -91,
    -1,   -91,    -2,   -69,   -75,   -91,   -46,   -45,   -91,   -49,
   -43,   -85,   -48,   -42,   -40,   -50,   -44,   -47,   -41,   -91,
   -34,   -75,   -16,   -12,   -13,   -15,   -91,   -73,   -91,    -3,
   -34,   -91,   -75,   -76,   -91,   -91,   -38,   -91,   -91,   -33,
   -35,   -91,   -89,   -91,   -83,   -91,   -91,   -91,   -74,   151,
   -31,   -23,   -25,   -89,   -29,   -21,   -91,   -27,   -30,   -32,
   -28,   -91,   -91,   -91,   -79,   -82,   -65,   -64,   -66,   -68,
   -67,   -91,   -53,   -91,   -56,   -59,   -91,   -91,   -58,   -91,
   -86,   -87,   -88,   -91,   -91,   -91,   -90,   -91,   -84,   -14,
   -91,   -91,   -24,   -91,   -34,   -91,   -77,   -78,   -91,   -91,
   -52,   -54,   -91,   -91,   -61,   -91,   -91,   -39,   -51,   -37,
   -19,   -36,   -91,   -72,   -17,   -22,   -18,   -20,   -70,   -80,
   -81,   -91,   -57,   -91,   -60,   -63,   -71,   -91,   -91,   -62,
   -55 ]

racc_goto_table = [
    20,    49,    38,    62,    27,    25,    42,    99,    45,    94,
    84,    47,    75,    73,    33,    44,   125,    77,    78,    89,
    89,    38,    79,    27,    56,    92,   105,   131,    95,    57,
    53,   111,    38,    33,    27,    59,    98,   113,    43,    68,
    91,    70,    51,    80,    33,    85,    94,    64,    63,    46,
    71,    38,    83,    27,   103,    74,    89,    42,    82,    45,
    19,    89,   121,    33,   nil,   nil,   109,   110,   131,   124,
   nil,   nil,   nil,   nil,   135,   143,   139,   137,   142,    77,
    78,   115,   nil,   nil,    79,   nil,   nil,   nil,    89,   nil,
   nil,    49,    38,   nil,    27,   127,    49,    38,   nil,    27,
   129,   nil,   nil,    70,    33,    80,   nil,   132,    89,    33,
   nil,    85,    38,    49,    27,   140,   149,    74,   nil,    38,
   nil,    27,   145,   nil,    33,   nil,   nil,   nil,   nil,    49,
   nil,    33,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   148 ]

racc_goto_check = [
     2,     3,    14,    18,     4,    26,    15,    29,    14,    35,
    44,    14,    21,    18,    20,    13,    38,    23,    24,    30,
    30,    14,    25,     4,    26,    33,    19,    27,    37,    28,
    42,    17,    14,    20,     4,    26,    36,    19,    12,    14,
    32,    15,    39,    14,    20,    14,    35,    42,    40,    41,
    16,    14,    43,     4,    26,    20,    30,    15,    42,    14,
     1,    30,    33,    20,   nil,   nil,    13,     2,    27,    37,
   nil,   nil,   nil,   nil,    21,    29,    44,    18,    35,    23,
    24,     2,   nil,   nil,    25,   nil,   nil,   nil,    30,   nil,
   nil,     3,    14,   nil,     4,    26,     3,    14,   nil,     4,
    26,   nil,   nil,    15,    20,    14,   nil,     2,    30,    20,
   nil,    14,    14,     3,     4,    26,    37,    20,   nil,    14,
   nil,     4,    26,   nil,    20,   nil,   nil,   nil,   nil,     3,
   nil,    20,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     2 ]

racc_goto_pointer = [
   nil,    60,     0,   -19,    -5,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    23,     0,    -7,    -9,     0,   -40,   -37,   -36,
     5,   -38,   nil,   -33,   -32,   -28,    -4,   -79,     1,   -50,
   -35,   nil,   -14,   -29,   nil,   -45,   -19,   -27,   -80,    18,
     7,    31,     6,     0,   -42 ]

racc_goto_default = [
   nil,   nil,   nil,    22,     1,     3,     6,     8,    10,    13,
    16,    17,   nil,   nil,    21,    26,   nil,   nil,   nil,   nil,
    12,   nil,    76,    34,    36,    37,   nil,    60,   nil,   nil,
    30,    32,   nil,   nil,    93,    97,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :LBRACK => 2,
 :QTEXT => 3,
 :RBRACK => 4,
 :LBRACE => 5,
 :RBRACE => 6,
 :SYMBOL => 7,
 :FARROW => 8,
 :COMMA => 9,
 :TRUE => 10,
 :FALSE => 11,
 :EQUALS => 12,
 :QMARK => 13,
 :LPAREN => 14,
 :RPAREN => 15,
 :ISEQUAL => 16,
 :GREATEREQUAL => 17,
 :GREATERTHAN => 18,
 :LESSTHAN => 19,
 :LESSEQUAL => 20,
 :NOTEQUAL => 21,
 :IF => 22,
 :ELSE => 23,
 :IMPORT => 24,
 :DEFINE => 25,
 :ELSIF => 26,
 :VARIABLE => 27,
 :CLASS => 28,
 :INHERITS => 29,
 :NODE => 30,
 :BOOLEAN => 31,
 :DOT => 32,
 :COLON => 33,
 :TYPE => 34,
 :NAME => 35,
 :SEMIC => 36,
 :CASE => 37,
 :DEFAULT => 38,
 :INCLUDE => 39 }

racc_use_result_var = true

racc_nt_base = 40

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'LBRACK',
'QTEXT',
'RBRACK',
'LBRACE',
'RBRACE',
'SYMBOL',
'FARROW',
'COMMA',
'TRUE',
'FALSE',
'EQUALS',
'QMARK',
'LPAREN',
'RPAREN',
'ISEQUAL',
'GREATEREQUAL',
'GREATERTHAN',
'LESSTHAN',
'LESSEQUAL',
'NOTEQUAL',
'IF',
'ELSE',
'IMPORT',
'DEFINE',
'ELSIF',
'VARIABLE',
'CLASS',
'INHERITS',
'NODE',
'BOOLEAN',
'DOT',
'COLON',
'TYPE',
'NAME',
'SEMIC',
'CASE',
'DEFAULT',
'INCLUDE',
'$start',
'program',
'statements',
'statement',
'object',
'assignment',
'casestatement',
'import',
'include',
'definition',
'hostclass',
'nodedef',
'classnames',
'classname',
'name',
'variable',
'objectinstances',
'endsemi',
'params',
'endcomma',
'type',
'objectinst',
'objectname',
'quotedtext',
'selector',
'array',
'rvalue',
'param',
'rvalues',
'comma',
'boolean',
'objectref',
'caseopts',
'caseopt',
'casevalues',
'selectlhand',
'svalues',
'selectval',
'sintvalues',
'argumentlist',
'parent',
'names',
'nothing',
'arguments',
'argument']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'grammar.ra', 40
  def _reduce_1( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :children => [val[0]]
        )
    end

    # this is mainly so we can test the parser separately from the
    # interpreter
    if Puppet[:parseonly]
        begin
            if Puppet[:debug]
                puts result.tree(0)
            end
        rescue NoMethodError => detail
            Puppet.err detail
            #exit(78)
        end
        #require 'puppet/parser/interpreter'
        #result = Puppet::Server.new(result)
    end
   result
  end
.,.,

 # reduce 2 omitted

module_eval <<'.,.,', 'grammar.ra', 54
  def _reduce_3( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[1])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :file => @lexer.file,
            :line => @lexer.line,
            :children => [val[0],val[1]]
        )
    end
   result
  end
.,.,

 # reduce 4 omitted

 # reduce 5 omitted

 # reduce 6 omitted

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

 # reduce 11 omitted

module_eval <<'.,.,', 'grammar.ra', 91
  def _reduce_12( val, _values, result )
    classnames = aryfy(val[1])

    klasses = []
    
    # Now just iterate over each of the class names and create a new
    # object instance.  FIXME This should probably eventually include
    # some kind of checking that the asked-for class is a defined class.
    classnames.each { |classname|
        emptyary = AST::ASTArray.new(:children => [])
        klasses << AST::ObjectDef.new(
            :pin => "{}",
            :line => @lexer.line,
            :file => @lexer.file,
            :type => classname,
            :params => emptyary
        )
    }
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => klasses
    )
   result
  end
.,.,

 # reduce 13 omitted

module_eval <<'.,.,', 'grammar.ra', 98
  def _reduce_14( val, _values, result )
    result = aryfy(val[0], val[2])
    result.line = @lexer.line
    result.file = @lexer.file
   result
  end
.,.,

 # reduce 15 omitted

 # reduce 16 omitted

module_eval <<'.,.,', 'grammar.ra', 132
  def _reduce_17( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        raise Puppet::ParseError, "Invalid name"
    end
    array = val[2]
    if array.is_a?(AST::ObjectInst)
        array = [array]
    end
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file
    )
    # this iterates across each specified objectinstance
    array.each { |instance|
        unless instance.is_a?(AST::ObjectInst)
            raise Puppet::Dev, "Got something that isn't an instance"
        end
        # now, i need to somehow differentiate between those things with
        # arrays in their names, and normal things
        result.push AST::ObjectDef.new(
            :pin => "{}",
            :line => @lexer.line,
            :file => @lexer.file,
            :type => val[0],
            :name => instance[0],
            :params => instance[1]
        )
    }
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 148
  def _reduce_18( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        Puppet.notice "invalid name"
        raise Puppet::ParseError, "Invalid name"
    end
    # an object but without a name
    # this cannot be an instance of a library type

    # the objects will autogenerate a name if we don't provide one
    result = AST::ObjectDef.new(
        :pin => "{}",
        :line => @lexer.line,
        :file => @lexer.file,
        :type => val[0],
        :params => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 160
  def _reduce_19( val, _values, result )
    # a template setting for a type
    if val[0].is_a?(AST::ASTArray)
        raise Puppet::ParseError, "Invalid type"
    end
    result = AST::TypeDefaults.new(
        :pin => "{}",
        :line => @lexer.line,
        :file => @lexer.file,
        :type => val[0],
        :params => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 168
  def _reduce_20( val, _values, result )
    result = AST::ObjectInst.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => [val[0],val[2]]
    )
   result
  end
.,.,

 # reduce 21 omitted

module_eval <<'.,.,', 'grammar.ra', 182
  def _reduce_22( val, _values, result )
    if val[0].is_a?(AST::ObjectInst)
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    else
        val[0].push val[2]
        result = val[0]
    end
   result
  end
.,.,

 # reduce 23 omitted

 # reduce 24 omitted

module_eval <<'.,.,', 'grammar.ra', 193
  def _reduce_25( val, _values, result )
    result = AST::Name.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 201
  def _reduce_26( val, _values, result )
    result = AST::Type.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

 # reduce 30 omitted

 # reduce 31 omitted

 # reduce 32 omitted

module_eval <<'.,.,', 'grammar.ra', 224
  def _reduce_33( val, _values, result )
    # this is distinct from referencing a variable
    variable = AST::Name.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0].sub(/^\$/,'')
    )
    result = AST::VarDef.new(
        :pin => "=",
        :line => @lexer.line,
        :file => @lexer.file,
        :name => variable,
        :value => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 233
  def _reduce_34( val, _values, result )
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => []
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 233
  def _reduce_35( val, _values, result )
 result = val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 246
  def _reduce_36( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[2])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 261
  def _reduce_37( val, _values, result )
    leaf = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
    result = AST::ObjectParam.new(
        :pin => "=>",
        :line => @lexer.line,
        :file => @lexer.file,
        :param => leaf,
        :value => val[2]
    )
   result
  end
.,.,

 # reduce 38 omitted

module_eval <<'.,.,', 'grammar.ra', 274
  def _reduce_39( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        result = val[0].push(val[2])
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

 # reduce 40 omitted

 # reduce 41 omitted

 # reduce 42 omitted

 # reduce 43 omitted

 # reduce 44 omitted

 # reduce 45 omitted

 # reduce 46 omitted

 # reduce 47 omitted

 # reduce 48 omitted

module_eval <<'.,.,', 'grammar.ra', 292
  def _reduce_49( val, _values, result )
    result = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 300
  def _reduce_50( val, _values, result )
    result = AST::Boolean.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 310
  def _reduce_51( val, _values, result )
    result = AST::ObjectRef.new(
        :pin => '[]',
        :line => @lexer.line,
        :file => @lexer.file,
        :type => val[0],
        :name => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 327
  def _reduce_52( val, _values, result )
    options = val[3]
    unless options.is_a?(AST::ASTArray)
        options = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[3]]
        )
    end
    result = AST::CaseStatement.new(
        :test => val[1],
        :options => val[3],
        :file => @lexer.file,
        :line => @lexer.line
    )
   result
  end
.,.,

 # reduce 53 omitted

module_eval <<'.,.,', 'grammar.ra', 341
  def _reduce_54( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push val[1]
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0], val[1]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 351
  def _reduce_55( val, _values, result )
    result = AST::CaseOpt.new(
        :pin => ":",
        :value => val[0],
        :file => @lexer.file,
        :line => @lexer.line,
        :statements => val[3]
    )
   result
  end
.,.,

 # reduce 56 omitted

module_eval <<'.,.,', 'grammar.ra', 365
  def _reduce_57( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[2])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 375
  def _reduce_58( val, _values, result )
    result = AST::Selector.new(
        :pin => "?",
        :line => @lexer.line,
        :file => @lexer.file,
        :param => val[0],
        :values => val[2]
    )
   result
  end
.,.,

 # reduce 59 omitted

module_eval <<'.,.,', 'grammar.ra', 377
  def _reduce_60( val, _values, result )
 result = val[1]
   result
  end
.,.,

 # reduce 61 omitted

module_eval <<'.,.,', 'grammar.ra', 392
  def _reduce_62( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[2])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 402
  def _reduce_63( val, _values, result )
    result = AST::ObjectParam.new(
        :pin => "=>",
        :line => @lexer.line,
        :file => @lexer.file,
        :param => val[0],
        :value => val[2]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 410
  def _reduce_64( val, _values, result )
    result = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 417
  def _reduce_65( val, _values, result )
    result = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 424
  def _reduce_66( val, _values, result )
    result = AST::String.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 431
  def _reduce_67( val, _values, result )
    result = AST::Default.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => val[0]
    )
   result
  end
.,.,

 # reduce 68 omitted

module_eval <<'.,.,', 'grammar.ra', 469
  def _reduce_69( val, _values, result )
    # importing files
    # yuk, i hate keywords
    # we'll probably have to have some kind of search path eventually
    # but for now, just use a path relative to the file doing the importing
    dir = @lexer.file.sub(%r{[^/]+$},'').sub(/\/$/, '')
    if dir == ""
        dir = "."
    end
    result = AST::ASTArray.new(
        :file => @lexer.file,
        :line => @lexer.line
    )
    Dir.chdir(dir) {
        Dir.glob(val[1]).each { |file|
            parser = Puppet::Parser::Parser.new()
            parser.stack = self.stack
            Puppet.debug("importing '%s'" % file)
            begin
                parser.file = file
            rescue Puppet::ImportError
                Puppet.warning(
                    "Importing %s would result in an import loop" %
                        File.join(dir, file)
                )
                result = AST::ASTArray.new(
                    :file => @lexer.file,
                    :line => @lexer.line
                )
                next
            end
            # push the results into the main result array
            result.push parser.parse
        }
    }
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 479
  def _reduce_70( val, _values, result )
    result = AST::CompDef.new(
        :name => AST::Name.new(:value => val[1], :line => @lexer.line),
        :args => val[2],
        :file => @lexer.file,
        :line => @lexer.line,
        :code => val[4]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 495
  def _reduce_71( val, _values, result )
        #:args => val[2],
    args = {
        :name => AST::Name.new(:value => val[1], :line => @lexer.line),
        :file => @lexer.file,
        :line => @lexer.line,
        :code => val[4]
    }
    # It'll be an ASTArray if we didn't get a parent
    if val[2].is_a?(AST::Name)
        args[:parentclass] = val[2]
    end
    result = AST::ClassDef.new(args)
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 515
  def _reduce_72( val, _values, result )
    unless val[1].is_a?(AST::ASTArray)
        val[1] = AST::ASTArray.new(
            :line => val[1].line,
            :file => val[1].file,
            :children => [val[1]]
        )
    end
    args = {
        :file => @lexer.file,
        :line => @lexer.line,
        :names => val[1],
        :code => val[4]
    }
    #if val[3].is_a?(AST::Name)
    #    args[:parentclass] = val[2]
    #end
    result = AST::NodeDef.new(args)
   result
  end
.,.,

 # reduce 73 omitted

module_eval <<'.,.,', 'grammar.ra', 529
  def _reduce_74( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        result = val[0]
        result.push val[1]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0], val[1]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 537
  def _reduce_75( val, _values, result )
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => []
    )
   result
  end
.,.,

 # reduce 76 omitted

module_eval <<'.,.,', 'grammar.ra', 542
  def _reduce_77( val, _values, result )
    result = val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 553
  def _reduce_78( val, _values, result )
    if val[1].is_a?(AST::ASTArray)
        result = val[1]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0]]
        )
    end
   result
  end
.,.,

 # reduce 79 omitted

module_eval <<'.,.,', 'grammar.ra', 567
  def _reduce_80( val, _values, result )
    if val[0].is_a?(AST::ASTArray)
        val[0].push(val[2])
        result = val[0]
    else
        result = AST::ASTArray.new(
            :line => @lexer.line,
            :file => @lexer.file,
            :children => [val[0],val[2]]
        )
    end
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 575
  def _reduce_81( val, _values, result )
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => [val[0],val[2]]
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 582
  def _reduce_82( val, _values, result )
    result = AST::ASTArray.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :children => [val[0]]
    )
   result
  end
.,.,

 # reduce 83 omitted

module_eval <<'.,.,', 'grammar.ra', 591
  def _reduce_84( val, _values, result )
    result = AST::Name.new(
        :value => val[1],
        :file => @lexer.file,
        :line => @lexer.line
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 600
  def _reduce_85( val, _values, result )
    name = val[0].sub(/^\$/,'')
    result = AST::Variable.new(
        :line => @lexer.line,
        :file => @lexer.file,
        :value => name
    )
   result
  end
.,.,

module_eval <<'.,.,', 'grammar.ra', 609
  def _reduce_86( val, _values, result )
    if val[1].is_a?(AST::ASTArray)
        result = val[1]
    else
        result = AST::ASTArray.new
        result.push val[1]
    end
   result
  end
.,.,

 # reduce 87 omitted

 # reduce 88 omitted

 # reduce 89 omitted

module_eval <<'.,.,', 'grammar.ra', 614
  def _reduce_90( val, _values, result )
 result = nil
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

    end   # class Parser

  end   # module Parser

end   # module Puppet
