#!/usr/bin/env ruby
#
# Script to print out when puppet ran successfully last
# AJ Christensen <aj@junglist.gen.nz>
#

require 'puppet'
require 'puppet/defaults'
require 'yaml'

Puppet[:config] = "/etc/puppet/puppet.conf"
Puppet.parse_config

print "puppetlast\n"

nodes = {}

factsdir = Puppet.settings.value(:vardir) + "/yaml/facts"

begin
  Dir.chdir(factsdir) if File.exists?(factsdir)
  Dir.glob("*.yaml").each do |yaml|
    data = YAML.load_file(yaml)
    age = Time.now - data.values[:_timestamp]
    nodes[data.name] = age.to_i
  end

  nodes.sort.each do |node,age|
    minutes = age / 60
    puts minutes.floor.to_s + ' minutes ago: ' + node 
  end

rescue
  puts 'error: ' + $!
end
