#!/bin/bash
#
# Restart puppet on network changes to pickup changes to /etc/resolv.conf
#
# https://projects.puppetlabs.com/issues/2776
# https://bugzilla.redhat.com/532085

[[ $2 =~ ^(up|down)$ ]] && /sbin/service puppet condrestart || :
