#!/usr/bin/env ruby
# Puppetlast, a script to output the last check-in time of nodes. Also outputs the cached configuration state, if expired or not.
#
# AJ "Fujin" Christensen <aj@junglist.gen.nz>
#
require 'puppet'

Puppet[:config] = "/etc/puppet/puppet.conf"
Puppet.parse_config
Puppet[:name] = "puppetmasterd"
Puppet::Node::Facts.terminus_class = :yaml

print "puppetlast\n"

nodes = {}

yfdir = Puppet.settings.value(:vardir) + "/yaml/facts"

if yfdir
   begin
      Dir.chdir(yfdir) do
         Dir.glob("*.yaml").each do |yaml|
            data = YAML.load_file(yaml)
            t = Time.now
            age = t - data.version
            nodes[data.name] = age.to_i
         end
      end

      nodes.sort.each do |node,age|
         minutes = age / 60 + 0.5
         print minutes.floor.to_s + ' minutes ago: ' + node + "\n"
      end

   rescue
      print 'error: ' + $! + "\n"
   end

Puppet::Node::Facts.search("*").sort.each do |node|
  puts "#{node.name} #{node.expired? ? 'cached expired, ' : ''}checked in #{((Time.now - node.values[:_timestamp]) / 60).floor} minutes ago"
end

