#!/bin/sh
#

# PROVIDE: puppetd
# REQUIRE: NETWORK
# KEYWORD: FreeBSD shutdown

. /etc/rc.subr

name=puppetd
rcvar=`set_rcvar`

# set defaults
command=/usr/local/bin/puppetd
pidfile="/var/run/$name.pid"
#required_files="/usr/local/etc/$name.conf"

# read configuration and set defaults
load_rc_config "$name"
: ${puppetd_enable="NO"}
: ${puppetd_config="/usr/local/etc/puppet.conf"}
: ${puppetd_flags=""}

command_args="--config $puppetd_config $puppetd_flags"

run_rc_command "$1"
