source "https://rubygems.org"

gem "beaker", :git => "git://github.com/jpartlow/beaker.git", :branch => "issue/master/with_puppet_running_on"
gem "rake"

group(:test) do
  gem "rspec", "~> 2.11.0", :require => false
  gem "mocha", "~> 0.10.5", :require => false
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
