source "https://rubygems.org"

gem "puppet_acceptance", :git => "git://github.com/jpartlow/puppet-acceptance.git", :branch => "issue/master/with_puppet_running_on"
gem "rake"

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
