require 'rake/clean'

REPO_CONFIGS_DIR = "repo-configs"
CLEAN.include('*.tar', REPO_CONFIGS_DIR)

namespace :ci do
  desc "Run the acceptance tests through the Jenkins CI system.  (Requires commit SHA to be put under test as environment variable: SHA='<sha>')"
  task :test do
    ENV['OPTIONS'] = (ENV['OPTIONS'] || "") + " --xml"
    ENV['TESTING_MODE'] = 'jenkins'
    sh "beaker -o config/options.rb #{ENV['OPTIONS'] || ''} -t #{ENV['TEST'] || '../../tests'}"
  end
end

namespace :standalone do
  desc "Bring up the vagrant environment.  Includes pre-puppet environment packages installation and cross node networking support (/etc/hosts munging)"
  task :up do
    sh "vagrant up"
  end

  desc "Completely destroy the vagrant instances."
  task :clean do
    sh "vagrant destroy -f"
  end

  task :ensure_good_private_key do
    sh "chmod 600 acceptance.priv"
  end

  desc "Bring up vagrant boxes and run the tests through the puppet-acceptance beaker harness.  Specify TEST='../../tests/foo' to customize which tests are to be run, and/or OPTIONS='bar' to pass options to beaker."
  task :test => [:up, :ensure_good_private_key] do
    ENV['TESTING_MODE'] = 'local'
    sh "beaker -o config/options.rb #{ENV['OPTIONS'] || ''} -t #{ENV['TEST'] || '../../tests'}"
  end
end

task :default do
  sh('rake -T')
end
