name: Backport merged pull request
on:
  pull_request_target:
    types: [labeled]
permissions:
  contents: write      # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Backport merged pull request
    runs-on: ubuntu-latest
    # For security reasons, we don't want to checkout and run arbitrary code when
    # using the pull_request_target trigger. So restrict this to cases where the
    # backport label is applied to an already merged PR.
    if: github.event.pull_request.merged && contains(github.event.label.name, 'backport')
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Create backport pull requests
        uses: korthout/backport-action@bd68141f079bd036e45ea8149bc9d174d5a04703 # v1
